import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowRight, ChevronRight, Clock3, ExternalLink, ShieldCheck, Sparkles, Star, Table2 } from 'lucide-react';
import { CategoryNav } from '@/components/category-nav';
import { ProductLogo } from '@/components/ProductLogo';
import { CATEGORIES, getCategoryByPathSlug, getCategoryHref, getCategoryPathSlug, getProductHref, getProductsByCategory, sortProducts, type Category, type Product } from '@/lib/products';
import { breadcrumbItem, canonicalUrl } from '@/lib/structured-data';
import { getPricingText, listBestFor } from '@/lib/comparisons';
import { categoryIntroduction, editorialFor } from '@/lib/category-guides';

export const revalidate = 86400;
type Props = { params: Promise<{ category: string }>; searchParams?: Promise<{ sort?: string }> };
type Pick = { badge: string; title: string; product: Product; reason: string };

export function generateStaticParams() { return CATEGORIES.map((category) => ({ category: getCategoryPathSlug(category) })); }
async function getCategoryData(pathSlug: string) { const category = getCategoryByPathSlug(pathSlug); if (!category) return null; return { category, products: await getProductsByCategory(category.slug) }; }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { category: pathSlug } = await params; const data = await getCategoryData(pathSlug); if (!data) return {};
  return { title: `Best ${data.category.name} Tools (${data.products.length} Reviewed)`, description: `Compare the best ${data.category.name.toLowerCase()} tools by price, features, setup time, use case, and rating. Includes expert picks, workflows, buyer guidance, and FAQs.`, alternates: { canonical: getCategoryHref(data.category) } };
}

export default async function CategoryPage({ params, searchParams }: Props) {
  const { category: pathSlug } = await params; const sort = (await searchParams)?.sort ?? 'rating'; const data = await getCategoryData(pathSlug); if (!data) notFound();
  const { category } = data; const products = sortProducts(data.products, sort); const ranked = sortProducts(data.products); const topProduct = ranked[0];
  const picks = buildPicks(ranked); const faq = buildFaq(category, ranked, picks); const schema = buildSchema(category, ranked, faq);
  return <main className="min-h-screen bg-radial-blue px-6 py-10 lg:px-8">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <div className="mx-auto max-w-7xl">
      <div className="flex flex-col gap-6 rounded-3xl border border-white/10 bg-white/[.05] p-5 lg:flex-row lg:items-center lg:justify-between"><Link href="/" className="text-lg font-bold text-white">AI Tool Hub</Link><CategoryNav compact /></div>
      <nav aria-label="Breadcrumb" className="mt-10 flex flex-wrap items-center gap-2 text-sm text-slate-300"><Link href="/" className="hover:text-white">Home</Link><ChevronRight className="h-4 w-4" /><Link href="/#categories" className="hover:text-white">Categories</Link><ChevronRight className="h-4 w-4" /><span className="font-semibold text-blue-200">{category.name}</span></nav>

      <section className="py-12" aria-labelledby="page-title"><p className="text-sm font-semibold uppercase tracking-[.3em] text-blue-300">Category guide · independently compared</p><h1 id="page-title" className="mt-4 text-5xl font-bold tracking-tight text-white sm:text-6xl">Best {category.name} Tools</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Compare {products.length} {category.name.toLowerCase()} tools for {category.intent ?? `${category.name.toLowerCase()} workflows`}. This living guide updates from our product taxonomy as reviews are added or recategorized.</p><div className="mt-8 flex flex-wrap gap-3 text-sm text-slate-200"><span className="rounded-full bg-blue-500/20 px-4 py-2 font-semibold text-blue-100">{products.length} reviews</span>{topProduct && <span className="rounded-full bg-white/[.08] px-4 py-2">Top rated: {topProduct.name}</span>}<span className="rounded-full bg-white/[.08] px-4 py-2">Updated {lastReviewed(ranked)}</span><span className="rounded-full bg-white/[.08] px-4 py-2">Server-rendered comparison</span></div></section>

      <CategoryIntroduction category={category} products={ranked} />
      <BestPicks picks={picks} />
      <Statistics products={ranked} />

      <section className="mt-20 grid gap-8 lg:grid-cols-[1fr_320px]" aria-labelledby="reviews-heading"><div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 id="reviews-heading" className="text-3xl font-bold text-white">Sortable review cards</h2><div className="flex flex-wrap gap-2 text-sm" aria-label="Sort products">{[['rating','Top rated'], ['reviews','Most reviewed'], ['newest','Newest'], ['name','A-Z']].map(([key, label]) => <Link key={key} href={`${getCategoryHref(category)}?sort=${key}#reviews-heading`} className={`focus-ring rounded-full px-3 py-2 ${sort === key ? 'bg-blue-500 text-white' : 'bg-white/[.08] text-slate-200 hover:text-white'}`}>{label}</Link>)}</div></div><div className="grid gap-5 md:grid-cols-2">{products.map((product) => <ProductCard key={product.slug} product={product} />)}{!products.length && <p className="rounded-3xl border border-white/10 bg-white/5 p-8 text-slate-300">Reviews are being prepared for this category. Explore the related categories below in the meantime.</p>}</div></div><aside className="h-fit rounded-3xl border border-white/10 bg-white/[.06] p-6"><h2 className="text-2xl font-bold text-white">Buying guide</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300"><li>Start with one workflow and a measurable result.</li><li>Compare total price, setup, platform support, collaboration, and governance—not just AI output.</li><li>Trial finalists on the same realistic task, then read their full reviews and limitations.</li></ul></aside></section>

      <WorkflowStacks category={category} products={ranked} />
      <BuyerPersonas category={category} products={ranked} />
      <DecisionTree category={category} products={ranked} />
      <FeatureMatrix products={ranked} />
      <RealWorkflows category={category} products={ranked} />
      <EditorsRecommendation category={category} picks={picks} />
      <InternalLinkHub category={category} products={ranked} />
      <PinterestIdeas category={category} />
      <RelatedGuides category={category} />
      <TrustSignals category={category} products={ranked} />
      <section className="mt-16 grid gap-6 lg:grid-cols-2"><Info title="How we evaluate tools" items={[`Product facts, review notes, pricing summaries, and use cases are pulled from each published profile in the taxonomy.`, `We prioritize fit for ${category.name.toLowerCase()}, transparent pricing, useful workflows, limitations, adoption effort, and evidence available in the product record.`, `Category pages regenerate as product JSON files and published reviews are added or updated.`]} /><FaqSection title={`${category.name} FAQs`} faq={faq} /></section>
    </div>
  </main>;
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) { return <div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.25em] text-blue-300">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold text-white sm:text-4xl">{title}</h2>{description && <p className="mt-4 leading-7 text-slate-300">{description}</p>}</div>; }
function CategoryIntroduction({ category, products }: { category: Category; products: Product[] }) { return <section className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-10" aria-labelledby="intro-heading"><SectionHeading eyebrow="Start here" title={`How to choose ${category.name.toLowerCase()} software`} description="A practical category briefing for first-time and experienced buyers." /><div id="intro-heading" className="mt-8 columns-1 gap-10 space-y-5 text-[1.02rem] leading-8 text-slate-300 lg:columns-2">{categoryIntroduction(category, products).map((paragraph) => <p key={paragraph.slice(0, 50)} className="break-inside-avoid">{paragraph}</p>)}</div></section>; }
function BestPicks({ picks }: { picks: Pick[] }) { if (!picks.length) return null; return <section className="mt-20" aria-labelledby="picks-heading"><SectionHeading eyebrow="Quick shortlist" title="Best picks by need" description="Selections are calculated from ratings, audience fit, setup time, pricing fields, features, and review volume." /><div id="picks-heading" className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{picks.map(({ badge, title, product, reason }) => <Link href={getProductHref(product)} key={title} className="glass focus-ring group rounded-3xl p-6 transition hover:-translate-y-1 hover:border-blue-300/60"><span className="text-2xl" aria-hidden>{badge}</span><p className="mt-4 text-sm font-semibold text-blue-200">{title}</p><div className="mt-3 flex items-center gap-3"><ProductLogo logo={product.logo} name={product.name} size={40} className="rounded-xl" /><h3 className="text-xl font-bold text-white">{product.name}</h3></div><p className="mt-4 text-sm leading-6 text-slate-300">{reason}</p></Link>)}</div></section>; }
function Statistics({ products }: { products: Product[] }) { const free = products.filter(hasFreePlan).length; const open = products.filter((p) => textFor(p).includes('open source')).length; const popular = [...products].sort((a,b)=>b.reviewCount-a.reviewCount)[0]; const newest = [...products].sort((a,b)=>dateOf(b)-dateOf(a))[0]; const updated = [...products].sort((a,b)=>modifiedOf(b)-modifiedOf(a))[0]; const stats = [['Products reviewed', products.length],['Average rating', products.length ? `${(products.reduce((n,p)=>n+p.rating,0)/products.length).toFixed(1)}/5` : '—'],['Free tools', free],['Paid tools', products.length-free],['Open source', open],['Most popular', popular?.name ?? '—'],['Newest', newest?.name ?? '—'],['Recently updated', updated?.name ?? '—']]; return <section className="mt-20 rounded-[2rem] border border-blue-300/20 bg-blue-500/10 p-6 sm:p-8" aria-labelledby="stats-heading"><h2 id="stats-heading" className="text-2xl font-bold text-white">Category statistics</h2><dl className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{stats.map(([label,value])=><div key={label} className="rounded-2xl bg-slate-950/40 p-4"><dt className="text-sm text-slate-300">{label}</dt><dd className="mt-2 text-xl font-bold text-white">{value}</dd></div>)}</dl></section>; }

function ProductCard({ product }: { product: Product }) { return <Link href={getProductHref(product)} className="glass focus-ring group flex h-full flex-col rounded-3xl p-6 transition hover:-translate-y-1 hover:border-blue-300/60"><div className="flex items-center gap-4"><ProductLogo logo={product.logo} name={product.name} size={56} className="rounded-2xl" /><div><h3 className="text-2xl font-semibold text-white">{product.name}</h3><p className="mt-1 flex items-center gap-2 text-sm text-blue-200"><Star className="h-4 w-4 fill-current" />{product.rating}/5 · {product.reviewCount.toLocaleString()} reviews</p></div></div><p className="mt-5 flex-1 text-slate-300">{product.description}</p><p className="mt-5 text-sm text-slate-300"><strong className="text-white">Best for:</strong> {listBestFor(product).join(', ')}</p><span className="mt-6 inline-flex items-center font-semibold text-blue-200 group-hover:text-white">Read full review <ArrowRight className="ml-2 h-4 w-4" /></span></Link>; }

function WorkflowStacks({ category, products }: { category: Category; products: Product[] }) { if (!products.length) return null; const e=editorialFor(category); const stacks=e.personas.slice(0,5).map((persona,i)=>({ persona, tools: rotate(products,i).slice(0,Math.min(4,products.length)) })); return <section className="mt-20" aria-labelledby="stacks-heading"><SectionHeading eyebrow="Connected systems" title={`${category.name} workflow recommendations`} description="Realistic multi-tool stacks for moving from input to finished work. Keep only the steps that remove a genuine handoff." /><div id="stacks-heading" className="mt-8 grid gap-5 lg:grid-cols-2">{stacks.map(({persona,tools})=><article key={persona} className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><h3 className="text-xl font-bold text-white">{persona} stack</h3><ol className="mt-5 space-y-3">{tools.map((tool,index)=><li key={tool.slug} className="relative flex gap-4 pb-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-500 font-bold text-white">{index+1}</span><div><Link href={getProductHref(tool)} className="font-semibold text-blue-200 hover:text-white">{tool.name}</Link><p className="mt-1 text-sm leading-6 text-slate-300">{workflowReason(tool,index,e.jobs)}</p></div></li>)}</ol></article>)}</div></section>; }
function BuyerPersonas({ category, products }: { category: Category; products: Product[] }) { if (!products.length) return null; const personas=editorialFor(category).personas; const premium=[...products].sort((a,b)=>premiumScore(b)-premiumScore(a))[0]; const budget=[...products].sort((a,b)=>Number(hasFreePlan(b))-Number(hasFreePlan(a)) || b.rating-a.rating)[0]; return <section className="mt-20" aria-labelledby="persona-heading"><SectionHeading eyebrow="Match the buyer" title="Recommendations by persona" description="The same winner rarely fits a first-time individual buyer and a governed team rollout." /><div id="persona-heading" className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{personas.map((persona,i)=>{const best=products[i%products.length]; return <article key={persona} className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><h3 className="text-xl font-bold text-white">{persona}</h3><RecommendationRow label="Best tool" product={best}/><RecommendationRow label="Budget tool" product={budget}/><RecommendationRow label="Premium tool" product={premium}/></article>})}</div></section>; }
function RecommendationRow({label,product}:{label:string;product:Product}) { return <div className="mt-4 flex items-center justify-between gap-3 border-t border-white/10 pt-4"><span className="text-sm text-slate-400">{label}</span><Link href={getProductHref(product)} className="font-semibold text-blue-200 hover:text-white">{product.name}</Link></div>; }
function DecisionTree({ category, products }: { category: Category; products: Product[] }) { if (!products.length) return null; const jobs=editorialFor(category).jobs; return <section className="mt-20 rounded-[2rem] border border-white/10 bg-gradient-to-br from-blue-500/15 to-violet-500/10 p-6 sm:p-10" aria-labelledby="tree-heading"><SectionHeading eyebrow="Choose with confidence" title={`A ${category.name.toLowerCase()} decision tree`} description="Begin with the job, then validate the recommendation against price and deployment requirements." /><div id="tree-heading" className="mt-8 flex flex-col items-center">{jobs.concat(['team rollout']).map((job,i)=>{const tool=products[i%products.length]; return <div key={job} className="contents"><div className="w-full max-w-2xl rounded-2xl border border-white/10 bg-slate-950/70 p-5 text-center"><p className="text-sm text-slate-300">Need help with {job}?</p><p className="mt-2 font-bold text-white">Yes → <Link href={getProductHref(tool)} className="text-blue-200 hover:text-white">Start with {tool.name}</Link></p><p className="mt-1 text-xs text-slate-400">Best-for signals: {listBestFor(tool).slice(0,2).join(', ')}</p></div>{i<jobs.length && <div className="h-9 w-px bg-blue-300/50" aria-hidden />}</div>})}</div></section>; }

function FeatureMatrix({ products }: { products: Product[] }) { return <section className="mt-20 rounded-3xl border border-white/10 bg-white/[.05] p-6" aria-labelledby="matrix-heading"><h2 id="matrix-heading" className="flex items-center gap-2 text-3xl font-bold text-white"><Table2 className="h-7 w-7 text-blue-300" />Feature and comparison matrix</h2><p className="mt-3 max-w-3xl text-slate-300">A dash means the published product record does not make the detail clear; confirm current capabilities and terms with the vendor.</p><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[1700px] text-left text-sm"><thead className="text-blue-200"><tr>{['Tool','Pricing','Free plan','Platforms','Integrations','Learning curve','AI quality','Collaboration','Templates','Automation','Enterprise ready','Best for','Setup time','Rating','Review count'].map(h=><th key={h} className="whitespace-nowrap py-3 pr-6">{h}</th>)}</tr></thead><tbody className="divide-y divide-white/10 text-slate-300">{products.map(p=><tr key={p.slug}><td className="py-4 pr-6 font-semibold text-white"><Link href={getProductHref(p)} className="hover:text-blue-200">{p.name}</Link></td><Cell>{getPricingText(p)}</Cell><Cell>{hasFreePlan(p)?'Yes':'Not listed'}</Cell><Cell>{p.platforms?.join(', ')||'—'}</Cell><Cell>{signal(p,'integrat')?'Available':'Not documented'}</Cell><Cell>{learningCurve(p)}</Cell><Cell>{p.ratings?.aiQuality ? `${p.ratings.aiQuality}/5` : `${p.rating}/5 editorial`}</Cell><Cell>{signal(p,'collaborat|team|shared')?'Yes':'Not documented'}</Cell><Cell>{signal(p,'template')?'Yes':'Not documented'}</Cell><Cell>{signal(p,'automat|workflow|agent')?'Yes':'Not documented'}</Cell><Cell>{signal(p,'enterprise|sso|governance|admin')?'Likely fit—verify':'Not documented'}</Cell><Cell>{listBestFor(p).slice(0,3).join(', ')}</Cell><Cell>{p.setupTime||'—'}</Cell><Cell>{p.rating}/5</Cell><Cell>{p.reviewCount.toLocaleString()}</Cell></tr>)}</tbody></table></div></section>; }
function Cell({children}:{children:React.ReactNode}) { return <td className="max-w-[220px] py-4 pr-6 align-top">{children}</td>; }

function RealWorkflows({ category, products }: { category: Category; products: Product[] }) { if (!products.length) return null; const names=['Daily workflow','Weekly workflow','Agency workflow','Teacher workflow','Business workflow','Creator workflow']; const jobs=editorialFor(category).jobs; return <section className="mt-20" aria-labelledby="real-heading"><SectionHeading eyebrow="Put it into practice" title="Real multi-tool workflows" description="Six operating rhythms showing where people review, hand off, and publish the work." /><div id="real-heading" className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{names.map((name,i)=>{const tools=rotate(products,i).slice(0,Math.min(3,products.length)); return <article key={name} className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><Clock3 className="h-6 w-6 text-blue-300"/><h3 className="mt-4 text-xl font-bold text-white">{name}</h3><p className="mt-3 text-sm leading-6 text-slate-300">Begin with {jobs[i%jobs.length]}. {tools.map(t=>t.name).join(' → ')} moves the work from preparation through production and review. A person checks the result before the final handoff.</p><div className="mt-5 flex flex-wrap gap-2">{tools.map(t=><Link key={t.slug} href={getProductHref(t)} className="rounded-full bg-blue-500/15 px-3 py-1 text-sm text-blue-200 hover:bg-blue-500/30">{t.name}</Link>)}</div></article>})}</div></section>; }
function EditorsRecommendation({ category, picks }: { category: Category; picks: Pick[] }) { if (!picks.length) return null; const overall=picks[0].product,budget=picks.find(p=>p.title==='Best Value')?.product??overall,premium=picks.find(p=>p.title==='Best Premium')?.product??overall,alternative=picks.find(p=>p.product.slug!==overall.slug)?.product??overall; return <section className="mt-20 overflow-hidden rounded-[2rem] border border-amber-300/30 bg-gradient-to-br from-amber-300/15 via-white/[.05] to-blue-500/10 p-6 sm:p-10" aria-labelledby="editor-heading"><div className="flex items-center gap-3 text-amber-200"><Sparkles/><span className="font-semibold uppercase tracking-[.2em]">Editor&apos;s recommendation</span></div><h2 id="editor-heading" className="mt-5 text-4xl font-bold text-white">{overall.name} is our best overall {category.name.toLowerCase()} pick</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><EditorFact title="Who should buy it" value={`Buy it when ${listBestFor(overall).slice(0,3).join(', ')} match the work you need to improve.`}/><EditorFact title="Who should skip it" value={overall.notFor?.[0]?.description ?? overall.cons?.[0] ?? 'Skip it if its workflow or plan limits do not match your requirements.'}/><EditorFact title="Alternative recommendation" value={alternative.name}/><EditorFact title="Budget recommendation" value={budget.name}/><EditorFact title="Premium recommendation" value={premium.name}/></div><Link href={getProductHref(overall)} className="focus-ring mt-8 inline-flex rounded-full bg-white px-6 py-3 font-bold text-slate-950 hover:bg-blue-100">Read the {overall.name} review <ArrowRight className="ml-2"/></Link></section>; }
function EditorFact({title,value}:{title:string;value:string}) { return <div className="rounded-2xl bg-slate-950/50 p-5"><h3 className="font-semibold text-amber-100">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{value}</p></div>; }

function InternalLinkHub({ category, products }: { category: Category; products: Product[] }) { const related=CATEGORIES.filter(c=>c.slug!==category.slug).slice(0,6); const comparisonPairs=products.slice(0,4).flatMap((p,i)=>products[i+1]?[{a:p,b:products[i+1]}]:[]); return <section className="mt-20" aria-labelledby="links-heading"><SectionHeading eyebrow="Continue your research" title="Internal link hub" description="Move between category shortlists, complete reviews, head-to-head comparisons, alternatives, ideas, stacks, and workflow reading."/><div id="links-heading" className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><LinkGroup title="Related categories" links={related.map(c=>({label:`Best ${c.name} tools`,href:getCategoryHref(c)}))}/><LinkGroup title="Related reviews" links={products.slice(0,6).map(p=>({label:`${p.name} review`,href:getProductHref(p)}))}/><LinkGroup title="Comparison pages" links={comparisonPairs.map(({a,b})=>({label:`${a.name} vs ${b.name}`,href:`/compare/${a.slug}-vs-${b.slug}`}))}/><LinkGroup title="Alternatives" links={products.slice(0,6).map(p=>({label:`Alternatives to ${p.name}`,href:`${getProductHref(p)}#alternatives`}))}/><LinkGroup title="Business ideas & starter stacks" links={[{label:`${category.name} business ideas`,href:`/search?q=${encodeURIComponent(category.name+' business')}`},{label:`Beginner ${category.name} stack`,href:'#stacks-heading'},{label:`Professional ${category.name} stack`,href:'#stacks-heading'}]}/><LinkGroup title="Workflow articles" links={[{label:`Daily ${category.name} workflow`,href:'#real-heading'},{label:`Weekly ${category.name} workflow`,href:'#real-heading'},{label:`How to choose ${category.name} tools`,href:'#intro-heading'}]}/></div></section>; }
function LinkGroup({title,links}:{title:string;links:{label:string;href:string}[]}) { return <div className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><h3 className="text-xl font-bold text-white">{title}</h3><ul className="mt-4 space-y-3">{links.length?links.map(l=><li key={l.label}><Link href={l.href} className="inline-flex items-center text-sm text-blue-200 hover:text-white">{l.label}<ExternalLink className="ml-2 h-3 w-3"/></Link></li>):<li className="text-sm text-slate-400">More links will appear as reviews are published.</li>}</ul></div>; }
function PinterestIdeas({ category }: { category: Category }) { const topic=category.name.replace(/^AI /,''); const ideas=[`How to save 10 hours with ${topic} tools`,`Best ${category.name} tools for beginners`,`${category.name} workflow checklist`,`${category.name} toolkit: what you actually need`,`5 ${category.name} business ideas`,`A one-week ${category.name} starter plan`]; return <section className="mt-20 rounded-[2rem] border border-rose-300/20 bg-rose-500/10 p-6 sm:p-10" aria-labelledby="ideas-heading"><SectionHeading eyebrow="Save-worthy ideas" title={`Popular ${category.name} guides and business ideas`} description="Visual, practical topics for planning a workflow or a small business offer."/><div id="ideas-heading" className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{ideas.map((idea,i)=><Link key={idea} href={`/search?q=${encodeURIComponent(idea)}`} className="focus-ring rounded-2xl bg-slate-950/60 p-5 font-semibold text-white transition hover:-translate-y-1"><span className="text-rose-300">0{i+1}</span><span className="mt-3 block">{idea}</span></Link>)}</div></section>; }
function RelatedGuides({ category }: { category: Category }) { const e=editorialFor(category); const guides=[`Best ${category.name} tools for ${e.audiences[0].toLowerCase()}s`,`${category.name} implementation guide`,`${category.name} workflow guide`,`${category.name} side-hustle ideas`,`How teams use ${category.name}`,`${category.name} buying checklist`]; return <section className="mt-20" aria-labelledby="guides-heading"><SectionHeading eyebrow="Learn before you buy" title="Related guides"/><div id="guides-heading" className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{guides.map(g=><Link key={g} href={`/search?q=${encodeURIComponent(g)}`} className="glass focus-ring rounded-2xl p-5 font-semibold text-white hover:border-blue-300/50">{g}<ArrowRight className="mt-4 h-5 w-5 text-blue-300"/></Link>)}</div></section>; }
function TrustSignals({ category, products }: { category: Category; products: Product[] }) { return <section className="mt-20 rounded-[2rem] border border-emerald-300/20 bg-emerald-500/[.08] p-6 sm:p-10" aria-labelledby="trust-heading"><SectionHeading eyebrow="Why trust this guide" title="Transparent review standards" description={`Last reviewed ${lastReviewed(products)} · ${products.length} products compared`}/><div id="trust-heading" className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[['How we review',`We compare published product records, documented features, pricing notes, use cases, and limitations for ${category.name.toLowerCase()} fit.`],['Editorial process','Recommendations are derived from consistent taxonomy signals, then presented with clear reasons and links to the underlying reviews.'],['Testing methodology','We use scenario-based comparison and never treat a vendor claim or generated output as proof of performance without supporting evidence.'],['Update history',`The page is statically generated and revalidates daily; product additions and modified review dates flow into its rankings and statistics.`]].map(([title,body])=><article key={title}><ShieldCheck className="h-7 w-7 text-emerald-300"/><h3 className="mt-4 font-bold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{body}</p></article>)}</div></section>; }
function Info({ title, items }: { title: string; items: string[] }) { return <section className="rounded-3xl border border-white/10 bg-white/[.06] p-6"><h2 className="text-3xl font-bold text-white">{title}</h2><div className="mt-5 space-y-4 text-slate-300">{items.map(item=><p key={item}>{item}</p>)}</div></section>; }
function FaqSection({title,faq}:{title:string;faq:{question:string;answer:string}[]}) { return <section className="rounded-3xl border border-white/10 bg-white/[.06] p-6"><h2 className="text-3xl font-bold text-white">{title}</h2><div className="mt-5 divide-y divide-white/10">{faq.map(item=><details key={item.question} className="group py-4"><summary className="focus-ring cursor-pointer list-none font-semibold text-white">{item.question}<span className="float-right text-blue-300 group-open:rotate-45">+</span></summary><p className="mt-3 leading-7 text-slate-300">{item.answer}</p></details>)}</div></section>; }

function buildPicks(products: Product[]): Pick[] { if (!products.length) return []; const choose=(score:(p:Product)=>number)=>[...products].sort((a,b)=>score(b)-score(a)||b.rating-a.rating)[0]; const defs:[string,string,Product,string][]=[['🏆','Best Overall',choose(p=>p.rating*20+Math.log10(p.reviewCount+1)*4),'The strongest blend of rating, review depth, and category fit.'],['💰','Best Value',choose(p=>p.rating*10+(hasFreePlan(p)?20:0)+(signal(p,'value')?4:0)),'A high-rated option with a free-plan or value signal in its profile.'],['🚀','Best for Beginners',choose(p=>p.rating*10+(signal(p,'beginner|easy|simple|template')?15:0)-setupMinutes(p)/30),'Approachable positioning and a comparatively quick path to a first result.'],['👨‍🏫','Best for Teachers',choose(p=>p.rating*10+(signal(p,'teacher|student|classroom|lesson|education')?25:0)),'The clearest documented fit for teaching, learning, or guided instruction.'],['🏢','Best for Business',choose(p=>p.rating*10+(signal(p,'business|team|enterprise|collaborat|admin')?18:0)),'Strong signals for team workflows, collaboration, or organizational use.'],['⚡','Fastest Setup',choose(p=>100-setupMinutes(p)+p.rating),'The shortest documented setup time, with rating used as a quality safeguard.'],['⭐','Best Premium',choose(p=>p.rating*10+premiumScore(p)),'The strongest fit for advanced, team, or enterprise requirements.']]; return defs.map(([badge,title,product,reason])=>({badge,title,product,reason})); }
function buildFaq(category:Category,products:Product[],picks:Pick[]) { const top=picks[0]?.product; return [{question:`What is the best ${category.name.toLowerCase()} tool?`,answer:top?`${top.name} is our best overall pick based on its current rating, review depth, and category fit. Your use case, budget, and governance needs can make another pick more suitable.`:`No products are currently published in this category; the list will populate from the taxonomy as reviews are added.`},{question:`How many ${category.name.toLowerCase()} tools did AIToolBet compare?`,answer:`This guide currently compares ${products.length} published product review${products.length===1?'':'s'}.`},{question:`Are there free ${category.name.toLowerCase()} tools?`,answer:`${products.filter(hasFreePlan).length} product${products.filter(hasFreePlan).length===1?'':'s'} in this comparison currently include a free-plan signal in the published pricing data. Confirm current limits with the vendor.`},{question:`How should I compare ${category.name.toLowerCase()} products?`,answer:'Run the same realistic task in each finalist and compare useful output, correction time, setup, integrations, collaboration, privacy, and total cost.'},{question:'How often is this buying guide updated?',answer:'The page is statically generated, revalidates daily, and reflects product taxonomy and published review updates.'}]; }
function buildSchema(category: Category, products: Product[], faq: { question: string; answer: string }[]) {
  const href = getCategoryHref(category);
  const modified = products.reduce((latest, product) => Math.max(latest, modifiedOf(product)), 0);
  return {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': ['CollectionPage', 'Article'], name: `Best ${category.name} Tools`, headline: `Best ${category.name} Tools: Buying Guide`, url: canonicalUrl(href), dateModified: modified ? new Date(modified).toISOString().slice(0, 10) : undefined, about: { '@type': 'Thing', name: category.name }, breadcrumb: { '@id': `${canonicalUrl(href)}#breadcrumb` }, mainEntity: { '@id': `${canonicalUrl(href)}#products` } },
      { '@type': 'BreadcrumbList', '@id': `${canonicalUrl(href)}#breadcrumb`, itemListElement: [breadcrumbItem(1, 'Home', '/'), breadcrumbItem(2, 'Categories', '/#categories'), breadcrumbItem(3, category.name, href)] },
      { '@type': 'ItemList', '@id': `${canonicalUrl(href)}#products`, numberOfItems: products.length, itemListElement: products.map((product, index) => ({ '@type': 'ListItem', position: index + 1, url: canonicalUrl(getProductHref(product)), name: product.name, item: { '@type': 'SoftwareApplication', name: product.name, applicationCategory: category.name, aggregateRating: { '@type': 'AggregateRating', ratingValue: product.rating, bestRating: 5, ratingCount: product.reviewCount } } })) },
      { '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
    ],
  };
}
function textFor(p:Product) { return [p.name,p.description,p.tagline,p.users,p.bestFor,...(p.tags??[]),...(p.platforms??[]),...(p.features??[]).flatMap(f=>[f.title,f.description]),...(p.audiences??[]).flatMap(a=>[a.title,a.description]),...p.pricingPlans.flatMap(x=>[x.name,x.description,...x.features])].join(' ').toLowerCase(); }
function signal(p:Product,pattern:string) { return new RegExp(pattern,'i').test(textFor(p)); }
function hasFreePlan(p:Product) { return typeof p.pricing==='object' ? Boolean(p.pricing.freePlan) : /free/i.test(p.pricing); }
function setupMinutes(p:Product) { const match=(p.setupTime||'').match(/(\d+)/); if (!match) return signal(p,'easy|simple|beginner')?30:90; const n=Number(match[1]); return /day/i.test(p.setupTime)?n*1440:/hour/i.test(p.setupTime)?n*60:n; }
function learningCurve(p:Product) { if (p.reviewerIntelligence?.learningCurve) return p.reviewerIntelligence.learningCurve; if (signal(p,'beginner|easy|simple|intuitive')) return 'Easy'; if (signal(p,'advanced|developer|enterprise')) return 'Moderate–advanced'; return 'Moderate'; }
function premiumScore(p:Product) { return (signal(p,'enterprise|advanced|professional|team|governance|admin')?20:0)+(p.pricingPlans?.length??0)+p.rating; }
function rotate<T>(items:T[],offset:number) { return [...items.slice(offset%items.length),...items.slice(0,offset%items.length)]; }
function workflowReason(p:Product,index:number,jobs:string[]) { const feature=p.features?.[index%Math.max(p.features.length,1)]; return index===0?`Use it to start ${jobs[index%jobs.length]}; ${feature?.description??p.description}`:index===1?`It turns the first tool's output into a more usable working asset. ${feature?.description??p.description}`:`It handles the ${index===2?'production and review':'final delivery'} stage. ${feature?.description??p.description}`; }
function dateOf(p:Product) { return Date.parse(p.review.datePublished)||0; }
function modifiedOf(p:Product) { return Date.parse(p.review.dateModified??p.review.datePublished)||0; }
function lastReviewed(products:Product[]) { const stamp=products.reduce((n,p)=>Math.max(n,modifiedOf(p)),0); return stamp?new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(stamp)):'July 31, 2026'; }
