import { promises as fs } from 'fs';
import path from 'path';
import type { ContentHealth, ContentIndexItem, ContentType, ReviewDraft } from './types';
import { getProduct, getProducts } from '@/lib/products';

const contentRoot = path.join(process.cwd(), 'content');
export const contentFolders = ['reviews', 'buying-guides', 'tutorials', 'alternatives'] as const;
export function contentPath(state: 'drafts' | 'published', type: ContentType, slug: string) { return path.join(contentRoot, state, type, `${slug}.json`); }
async function readJson<T>(file: string): Promise<T | null> { try { return JSON.parse(await fs.readFile(file, 'utf8')) as T; } catch { return null; } }
export async function readReviewDraft(slug: string, state: 'drafts' | 'published' = 'drafts') { return readJson<ReviewDraft>(contentPath(state, 'reviews', slug)); }
export async function writeReviewDraft(draft: ReviewDraft, state: 'drafts' | 'published' = 'drafts') { const file = contentPath(state, 'reviews', draft.slug); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, `${JSON.stringify(draft, null, 2)}\n`); return file; }
export async function publishReview(slug: string) { const draft = await readReviewDraft(slug, 'drafts'); if (!draft) throw new Error(`No draft found for ${slug}`); const published = { ...draft, status: 'published' as const, updatedAt: new Date().toISOString() }; const target = await writeReviewDraft(published, 'published'); await fs.unlink(contentPath('drafts', 'reviews', slug)).catch(() => undefined); return target; }
export async function getPublishedReviewProduct(slug: string) { const product = await getProduct(slug); if (!product) return null; const content = await readReviewDraft(slug, 'published'); if (!content) return product; return { ...product, overview: asStringArray(content.sections.overview.content) ?? product.overview, pros: asStringArray(content.sections.pros.content) ?? product.pros, cons: asStringArray(content.sections.cons.content) ?? product.cons, audiences: sectionCards(content.sections.whoShouldBuy.content) ?? product.audiences, notFor: sectionCards(content.sections.whoShouldAvoid.content) ?? product.notFor, useCases: asStringArray(content.sections.useCases.content) ?? product.useCases, faq: faq(content.sections.faq.content) ?? product.faq, verdict: typeof content.sections.verdict.content === 'string' ? content.sections.verdict.content : product.verdict, review: { ...product.review, summary: typeof content.sections.verdict.content === 'string' ? content.sections.verdict.content : product.review.summary } }; }
export async function getContentIndex(): Promise<ContentIndexItem[]> { const products = await getProducts(); return Promise.all(products.map(async (product) => { const draft = await readReviewDraft(product.slug, 'drafts'); const published = await readReviewDraft(product.slug, 'published'); const active = draft ?? published; const missing = !product.pricing || !product.features?.length || !product.pros?.length || !product.cons?.length; return { productSlug: product.slug, productName: product.name, status: missing ? 'Missing Data' : published ? 'Published' : draft?.status === 'needs_review' ? 'Needs Review' : draft ? 'Draft' : 'Needs Regeneration', draftPath: draft ? `content/drafts/reviews/${product.slug}.json` : undefined, publishedPath: published ? `content/published/reviews/${product.slug}.json` : undefined, generatedDate: active?.metadata?.generatedDate ?? active?.generatedAt, model: active?.metadata?.model ?? active?.model, seoScore: scoreSeo(product.name, active?.seo.title ?? product.seoTitle, active?.seo.metaDescription ?? product.metaDescription ?? product.description), qualityScore: active?.quality?.overall, missingCount: active?.missingContent?.missing.length ?? 0 }; })); }
export async function getContentHealth(): Promise<ContentHealth> { const products = await getProducts(); const items = await Promise.all(products.map(async (product) => ({ product, draft: await readReviewDraft(product.slug, 'drafts'), published: await readReviewDraft(product.slug, 'published') }))); const active = items.map((item) => item.draft ?? item.published).filter(Boolean) as ReviewDraft[]; const averageReviewScore = Math.round(active.reduce((sum, draft) => sum + (draft.quality?.overall ?? 0), 0) / Math.max(active.length, 1)); const count = (fn: (item: typeof items[number]) => boolean) => items.filter(fn).length; return { overallSiteScore: Math.round((averageReviewScore + Math.round(((products.length - count((item) => !item.draft && !item.published)) / Math.max(products.length, 1)) * 100)) / 2), averageReviewScore, productsMissingReviews: count((item) => !item.draft && !item.published), productsMissingComparisons: count((item) => !(item.draft ?? item.published)?.assets?.comparison?.length && !item.product.comparison?.length), productsMissingAlternatives: count((item) => !(item.draft ?? item.published)?.assets?.alternatives?.length && !item.product.alternatives?.length), productsMissingBuyingGuideData: count((item) => !(item.draft ?? item.published)?.assets?.buyingGuide?.length), productsMissingImages: count((item) => !item.product.screenshots?.length && !item.product.heroImage), productsMissingFaqs: count((item) => !item.product.faq?.length && !(item.draft ?? item.published)?.sections?.faq), productsMissingSeo: count((item) => !item.product.seoTitle && !item.product.metaDescription && !(item.draft ?? item.published)?.seo) }; }
function scoreSeo(name: string, title?: string, description?: string) { let score = 0; if (title && title.length >= 35 && title.length <= 70) score += 40; if (description && description.length >= 120 && description.length <= 165) score += 40; if (title?.toLowerCase().includes(name.toLowerCase())) score += 20; return score; }
function asStringArray(value: unknown) { if (Array.isArray(value) && value.every((x) => typeof x === 'string')) return value; if (typeof value === 'string') return value.split('\n').map((x) => x.trim()).filter(Boolean); return null; }
function faq(value: unknown) { return Array.isArray(value) && value.every((x) => x && typeof x.question === 'string' && typeof x.answer === 'string') ? value as { question: string; answer: string }[] : null; }
function sectionCards(value: unknown) { const items = asStringArray(value); return items?.map((item) => ({ title: item.split(':')[0].slice(0, 48), description: item.includes(':') ? item.split(':').slice(1).join(':').trim() : item })); }
