import type { Product } from '@/lib/products';

export type ContentType = 'reviews' | 'buying-guides' | 'tutorials' | 'alternatives';
export type ReviewSectionKey = 'overview' | 'pros' | 'cons' | 'pricingSummary' | 'whoShouldBuy' | 'whoShouldAvoid' | 'useCases' | 'faq' | 'verdict';
export type GeneratedSection = { key: ReviewSectionKey; title: string; content: string | string[] | { question: string; answer: string }[]; generatedAt: string; model: string; sourceFields: string[] };
export type SeoAsset = { title: string; metaDescription: string; canonical: string; openGraphDescription?: string; twitterDescription?: string; searchSnippet?: string; shortSummary?: string; longSummary?: string; scores?: { uniqueness: number; keywordCoverage: number; contentCompleteness: number } };
export type QualityScore = { specificity: number; readability: number; productRelevance: number; seoCoverage: number; contentDepth: number; internalLinking: number; factualAccuracy: number; uniqueness: number; unsupportedClaims: number; overall: number; recommendations: string[] };
export type MissingContentReport = { missing: string[]; recommendations: string[] };
export type BuyingGuideSnippet = { category: string; whyMadeTheList: string; bestUseCase: string; whoShouldSkip: string; topCompetitor?: string; quickSummary: string };
export type ComparisonSummary = { competitorSlug: string; competitorName: string; mainDifference: string; whenProductWins: string; whenCompetitorWins: string; recommendation: string };
export type AlternativeSummary = { slug: string; name: string; bestFor: string; biggestStrength: string; biggestWeakness: string; whySomeoneWouldSwitch: string };
export type UtilizationCoverageItem = { used: number; total: number; notes?: string[] };
export type KnowledgeGraphUtilizationReport = {
  features: UtilizationCoverageItem;
  pros: UtilizationCoverageItem;
  cons: UtilizationCoverageItem;
  reviewerIntelligence: UtilizationCoverageItem;
  workflows: UtilizationCoverageItem;
  alternatives: UtilizationCoverageItem;
  pricingGuidance: UtilizationCoverageItem;
  buyerAdvice: UtilizationCoverageItem;
  strengths: UtilizationCoverageItem;
  weaknesses: UtilizationCoverageItem;
  pricingTradeoffs: UtilizationCoverageItem;
  examples: UtilizationCoverageItem;
  overallCoverage: number;
  omittedItems: string[];
  regenerationRecommended: boolean;
};
export type SectionInformationGain = { section: ReviewSectionKey; newFactsIntroduced: number; repeatedIdeas: string[]; repeatedSentences: string[]; repeatedExamples: string[]; repeatedWorkflows: string[]; passed: boolean; notes?: string };
export type GeneratedContentAssets = { buyingGuide?: BuyingGuideSnippet[]; alternatives?: AlternativeSummary[]; comparison?: ComparisonSummary[]; tutorial?: { title: string; steps: string[]; summary: string }; quality?: QualityScore; missingContent?: MissingContentReport; utilizationReport?: KnowledgeGraphUtilizationReport; informationGain?: SectionInformationGain[] };
export type GenerationMetadata = { promptVersion: string; generatedDate: string; model: string; provider: string; providerVersion: string; cacheHash: string; sourceHash: string; cached: boolean };
export type ReviewDraft = { type: 'review'; slug: string; productSlug: string; status: 'draft' | 'needs_review' | 'approved' | 'published'; generatedAt: string; updatedAt: string; model: string; seo: SeoAsset; sections: Record<ReviewSectionKey, GeneratedSection>; productSnapshot: Pick<Product, 'slug' | 'name' | 'rating' | 'pricing' | 'categories' | 'platforms' | 'affiliateLink' | 'logo' | 'features'>; assets?: GeneratedContentAssets; quality?: QualityScore; missingContent?: MissingContentReport; metadata?: GenerationMetadata; humanReview?: { reviewedBy?: string; reviewedAt?: string; notes?: string } };
export type ContentIndexItem = { productSlug: string; productName: string; status: 'Missing Data' | 'Needs Review' | 'Draft' | 'Published' | 'Needs Regeneration'; draftPath?: string; publishedPath?: string; generatedDate?: string; model?: string; seoScore: number; qualityScore?: number; missingCount: number };
export type ContentHealth = { overallSiteScore: number; averageReviewScore: number; productsMissingReviews: number; productsMissingComparisons: number; productsMissingAlternatives: number; productsMissingBuyingGuideData: number; productsMissingImages: number; productsMissingFaqs: number; productsMissingSeo: number };
