import Image from 'next/image';
import Link from 'next/link';
import { AlertTriangle, Bot, Brain, ChartBar, Check, ChevronDown, Code, FileText, FolderKanban, Image as ImageIcon, MessageCircle, Mic, Plug, Search, Star, Upload, XCircle } from 'lucide-react';
import type { Product } from '@/lib/products';
import { AffiliateButton } from './affiliate-button';
import { FloatingCta } from './floating-cta';

const icons = { MessageCircle, Code, FileText, Image: ImageIcon, Mic, Search, Bot, Upload, ChartBar, Plug, Brain, FolderKanban };

type NamedItem = { title: string; description: string };
type Alternative = { name: string; slug: string; logo: string; description: string };
type ComparisonMatrix = { columns: string[]; rows: { feature: string; values: string[] }[] };

export function ProductTemplate({ product, relatedProducts }: { product: Product; relatedProducts?: Product[] }) {
  const quickFacts = product.quickFacts ?? [
    { label: 'Setup Time', value: product.setupTime },
    { label: 'Pricing', value: product.pricing },
    { label: 'Platforms', value: product.platforms.join(', ') },
    { label: 'Best For', value: product.bestFor },
    { label: 'Overall Rating', value: `${product.rating} / 5` },
  ];
  const productSchema = { '@context': 'https://schema.org', '@type': 'Product', name: product.name, description: product.description, image: product.heroImage, brand: { '@type': 'Brand', name: product.name }, aggregateRating: { '@type': 'AggregateRating', ratingValue: product.rating, bestRating: 5, reviewCount: product.reviewCount }, review: { '@type': 'Review', author: { '@type': 'Organization', name: product.review.author }, datePublished: product.review.datePublished, name: product.review.title, reviewBody: product.review.summary, reviewRating: { '@type': 'Rating', ratingValue: product.rating, bestRating: 5 } }, offers: { '@type': 'Offer', url: product.affiliateLink, price: product.pricing, availability: 'https://schema.org/InStock' } };
  const reviewSchema = { '@context': 'https://schema.org', '@type': 'Review', itemReviewed: { '@type': 'Product', name: product.name, image: product.heroImage, description: product.description }, author: { '@type': 'Organization', name: product.review.author }, datePublished: product.review.datePublished, name: product.review.title, reviewBody: product.review.summary, reviewRating: { '@type': 'Rating', ratingValue: product.rating, bestRating: 5 } };
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: product.faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };

  return <main className="min-h-screen overflow-hidden bg-radial-blue pb-20 md:pb-0">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(reviewSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <Navbar product={product} />
    <Hero product={product} />
    <Section id="quick-facts" eyebrow="Quick facts" title={`${product.name} at a glance`}><FactGrid items={quickFacts} /></Section>
    <Section id="overview" eyebrow="Overview" title={`What is ${product.name}?`}><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-5 text-lg leading-8 text-slate-300">{(product.overview ?? [product.description]).map((p) => <p key={p}>{p}</p>)}</div><VerdictMini product={product} /></div></Section>
    <Section id="features" eyebrow="Features" title="Key Features"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{product.features.map((feature) => { const Icon = icons[feature.icon as keyof typeof icons] ?? Bot; return <Card key={feature.title}><Icon className="mb-5 h-6 w-6 text-blue-300" /><h3 className="text-xl font-semibold text-white">{feature.title}</h3><p className="mt-3 text-slate-300">{feature.description}</p></Card>; })}</div><CenterCta href={product.affiliateLink}>Try {product.name} after comparing features</CenterCta></Section>
    <Section eyebrow="Pros & Cons" title={`A balanced ${product.name} review`}><div className="grid gap-6 lg:grid-cols-2"><ListCard title="Pros" items={product.pros} tone="pro" /><ListCard title="Cons" items={product.cons} tone="con" /></div></Section>
    <Section id="pricing" eyebrow="Pricing" title={`${product.name} pricing plans`}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{product.pricingPlans.map((plan) => <Card key={plan.name}><h3 className="text-2xl font-semibold">{plan.name}</h3><p className="mt-2 text-3xl font-bold text-white">{plan.price}</p><p className="mt-3 text-sm text-slate-300">{plan.description}</p><ul className="my-6 space-y-3">{plan.features.map((item) => <li key={item} className="flex gap-2 text-sm text-slate-200"><Check className="h-5 w-5 shrink-0 text-blue-300" />{item}</li>)}</ul><AffiliateButton href={product.affiliateLink}>{plan.cta}</AffiliateButton></Card>)}</div></Section>
    <Section eyebrow="Best fit" title={`Who should use ${product.name}`}><CardGrid items={product.audiences} /></Section>
    <Section eyebrow="Not a fit" title={`Who should skip ${product.name}`}><CardGrid items={product.notFor} warning /></Section>
    <Section eyebrow="Use cases" title={`Real-world ways to use ${product.name}`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(product.useCases ?? []).map((item) => <Card key={item}><SparkLabel>{item}</SparkLabel><p className="mt-3 text-sm text-slate-300">Use {product.name} to move from blank page to structured first draft, then refine with your expertise.</p></Card>)}</div></Section>
    <Section id="alternatives" eyebrow="Alternatives" title={`${product.name} alternatives to compare`}><Alternatives items={product.alternatives ?? []} /></Section>
    <Section id="comparison" eyebrow="Comparison" title={`${product.name} comparison table`}><Comparison matrix={product.comparisonMatrix} productName={product.name} /></Section>
    <Section id="faq" eyebrow="FAQ" title="Frequently asked questions"><div className="mx-auto max-w-3xl space-y-3">{product.faq.map((item) => <details key={item.question} className="glass group rounded-2xl p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-white">{item.question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180" /></summary><p className="mt-4 text-slate-300">{item.answer}</p></details>)}</div></Section>
    <Section eyebrow="Final verdict" title={`Should you use ${product.name} in 2026?`}><Verdict product={product} /></Section>
    <RelatedReviews product={product} relatedProducts={relatedProducts ?? []} />
    <Footer product={product} />
    <FloatingCta href={product.affiliateLink} productName={product.name} />
  </main>;
}

function Navbar({ product }: { product: Product }) { return <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-slate-950/70 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"><Link href={`/${product.slug}`} className="flex items-center gap-3 font-semibold"><Image src={product.logo} alt={`${product.name} logo`} width={32} height={32} className="rounded-lg" />{product.name}</Link><div className="hidden gap-6 text-sm text-slate-300 md:flex"><a href="#features">Features</a><a href="#comparison">Compare</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div><AffiliateButton href={product.affiliateLink}>Try Now</AffiliateButton></div></nav>; }
function Hero({ product }: { product: Product }) { return <section className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-16 pt-32 lg:grid-cols-2 lg:px-8 lg:pt-40"><div><div className="mb-6 inline-flex items-center gap-3 rounded-full border border-blue-300/20 bg-blue-400/10 px-4 py-2 text-sm font-semibold text-blue-200"><Image src={product.logo} alt={`${product.name} logo`} width={24} height={24} className="rounded-md" />{product.categoryBadge ?? 'AI Assistant'}</div><h1 className="text-5xl font-bold tracking-tight text-white sm:text-7xl">{product.review.title}</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-slate-300">{product.tagline}.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><AffiliateButton href={product.affiliateLink}>Try {product.name}</AffiliateButton><a href="#overview" className="rounded-full border border-white/15 px-6 py-3 text-center font-semibold text-white transition hover:border-blue-300/50">Read Full Review</a></div></div><div className="glass rounded-[2rem] p-3 shadow-2xl shadow-blue-950/40"><Image src={product.heroImage} alt={`${product.name} application screenshot`} width={1600} height={1000} className="rounded-[1.5rem] border border-white/10" priority /></div></section>; }
function Section({ id, eyebrow, title, children }: { id?: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[.3em] text-blue-300">{eyebrow}</p><h2 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-5xl">{title}</h2><div className="mt-10">{children}</div></section>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="glass rounded-3xl p-6">{children}</div>; }
function FactGrid({ items }: { items: { label: string; value: string }[] }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Card key={item.label}><p className="text-sm font-semibold uppercase tracking-[.2em] text-blue-300">{item.label}</p><p className="mt-3 text-2xl font-bold text-white">{item.value}</p></Card>)}</div>; }
function ListCard({ title, items, tone }: { title: string; items: string[]; tone: 'pro' | 'con' }) { return <Card><h3 className="text-2xl font-semibold">{title}</h3><ul className="mt-6 space-y-4">{items.map((item) => <li key={item} className="flex gap-3 text-slate-200">{tone === 'pro' ? <Check className="h-6 w-6 shrink-0 text-emerald-300" /> : <AlertTriangle className="h-6 w-6 shrink-0 text-amber-300" />}{item}</li>)}</ul></Card>; }
function CardGrid({ items, warning }: { items: NamedItem[]; warning?: boolean }) { return <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{items.map((item) => <Card key={item.title}>{warning && <XCircle className="mb-5 h-6 w-6 text-amber-300" />}<h3 className="text-xl font-semibold">{item.title}</h3><p className="mt-3 text-slate-300">{item.description}</p></Card>)}</div>; }
function RelatedReviews({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { if (relatedProducts.length === 0) return null; return <Section eyebrow="Related reviews" title={`More ${product.categoryBadge?.toLowerCase() ?? 'software'} reviews to compare`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{relatedProducts.map((tool) => <Link key={tool.slug} href={`/${tool.slug}`} className="glass rounded-3xl p-6 transition hover:border-blue-300/40"><Image src={tool.logo} alt={`${tool.name} logo`} width={40} height={40} className="rounded-xl" /><h3 className="mt-5 text-xl font-semibold text-white">{tool.name}</h3><p className="mt-3 text-sm text-slate-300">{tool.tagline}</p><p className="mt-4 text-sm font-semibold text-blue-200">Read Review →</p></Link>)}</div></Section>; }
function Alternatives({ items }: { items: Alternative[] }) { return <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{items.map((item) => <Card key={item.name}><Image src={item.logo} alt={`${item.name} logo`} width={48} height={48} className="rounded-xl" /><h3 className="mt-5 text-xl font-semibold">{item.name}</h3><p className="mt-3 min-h-24 text-sm text-slate-300">{item.description}</p><Link href={`/${item.slug}`} className="mt-5 inline-flex rounded-full border border-white/15 px-4 py-2 text-sm font-semibold text-white">Read Review</Link></Card>)}</div>; }
function Comparison({ matrix, productName }: { matrix?: ComparisonMatrix; productName: string }) { const columns = matrix?.columns ?? [productName]; const rows = matrix?.rows ?? []; return <div className="overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[760px] text-left"><thead className="bg-white/5 text-white"><tr>{['Feature', ...columns].map((h) => <th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.feature} className="border-t border-white/10 text-slate-300"><th className="px-5 py-4 text-white">{row.feature}</th>{columns.map((column, index) => <td key={`${row.feature}-${column}`} className="px-5 py-4">{row.values[index] ?? '—'}</td>)}</tr>)}</tbody></table></div>; }
function VerdictMini({ product }: { product: Product }) { return <Card><div className="flex text-blue-300">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="h-5 w-5 fill-current" />)}</div><p className="mt-4 text-3xl font-bold text-white">{product.rating}/5</p><p className="mt-3 text-slate-300">Best for {product.bestFor.toLowerCase()}.</p><CenterCta href={product.affiliateLink}>Try {product.name} →</CenterCta></Card>; }
function Verdict({ product }: { product: Product }) { return <div className="glass rounded-[2rem] p-8 lg:p-10"><div className="grid gap-8 lg:grid-cols-[280px_1fr]"><div><p className="text-sm uppercase tracking-[.3em] text-blue-300">Overall Rating</p><p className="mt-3 text-6xl font-bold text-white">{product.rating}</p><p className="text-slate-300">out of 5</p></div><div><h3 className="text-3xl font-bold text-white">Our recommendation</h3><p className="mt-4 text-lg leading-8 text-slate-300">{product.review.summary} Key strengths include {product.pros.slice(0, 3).join(', ').toLowerCase()}. Key limitations include {product.cons.slice(0, 2).join(', ').toLowerCase()}.</p><p className="mt-4 text-slate-200"><strong>Best for:</strong> {product.bestFor}.</p><div className="mt-8"><AffiliateButton href={product.affiliateLink}>Try {product.name} →</AffiliateButton></div></div></div></div>; }
function SparkLabel({ children }: { children: React.ReactNode }) { return <h3 className="text-xl font-semibold text-white">{children}</h3>; }
function CenterCta({ href, children }: { href: string; children: React.ReactNode }) { return <div className="mt-8 text-center"><AffiliateButton href={href}>{children}</AffiliateButton></div>; }
function Footer({ product }: { product: Product }) { return <footer className="border-t border-white/10 px-6 py-10 text-center text-sm text-slate-400">© {new Date().getFullYear()} {product.name} review. Affiliate disclosure: links may be sponsored.</footer>; }
