import Link from 'next/link';
import { AlertTriangle, Bot, Brain, BriefcaseBusiness, ChartBar, Check, ChevronDown, Code, FileText, FolderKanban, GraduationCap, Image as ImageIcon, Lightbulb, Mail, MessageCircle, Mic, Plug, Rocket, Search, Star, Target, Upload, XCircle, Zap } from 'lucide-react';
import { getProductHref, type Product } from '@/lib/products';
import { getComparisonSlug, getPricingText } from '@/lib/comparisons';
import { buildProductReviewJsonLd } from '@/lib/structured-data';
import { AffiliateButton } from './affiliate-button';
import { FloatingCta } from './floating-cta';
import { ProductLogo } from './ProductLogo';
import { ScreenshotImage } from './ScreenshotImage';

const icons = { MessageCircle, Code, FileText, Image: ImageIcon, Mic, Search, Bot, Upload, ChartBar, Plug, Brain, FolderKanban };
const galleryEnabledSlugs = new Set(['chatgpt', 'claude', 'canva', 'cursor']);
const minimumGalleryScreenshots = 4;

function shouldShowScreenshotGallery(product: Product) {
  return galleryEnabledSlugs.has(product.slug) && (product.screenshots?.length ?? 0) >= minimumGalleryScreenshots;
}

const defaultRelatedRecommendations = [
  { slug: 'chatgpt', reason: 'for planning, outlines, briefs, and reusable client copy' },
  { slug: 'canva', reason: 'for simple client graphics, social posts, and presentation assets' },
  { slug: 'mailerlite', reason: 'for email marketing, lead magnets, and follow-up sequences' },
  { slug: 'grammarly', reason: 'for proofreading client-facing writing before delivery' },
  { slug: 'notion', reason: 'for organizing projects, deliverables, and repeatable workflows' },
  { slug: 'shopify', reason: 'for selling digital products, templates, or ecommerce offers' },
];

const sideHustleProfiles: Record<string, Partial<SideHustleProfile>> = {
  chatgpt: { ideas: [idea('Resume and LinkedIn writing service', 'Job seekers who need clearer applications but cannot afford a full career coach.', 'Rewrite resumes, LinkedIn summaries, cover letters, and interview prep notes from each client’s real background.', 'ChatGPT helps turn rough work history into stronger drafts, role-specific bullet points, and interview practice questions while you keep the final edit human and accurate.', '$0–$25 to start if you use an existing computer and a basic website or marketplace profile.', 'Beginner', '$50–$300 per project depending on scope, revisions, and niche.', ['Create three sample before-and-after resume sections.', 'Offer a small fixed-scope package to local job seekers or on a freelance marketplace.', 'Use a client questionnaire so every draft is based on real experience.']), idea('Blog and newsletter drafting service', 'Small businesses that need consistent educational content but do not have an in-house writer.', 'Create outlines, first drafts, topic clusters, and newsletter drafts, then fact-check and polish them for publication.', 'ChatGPT is useful for moving from blank page to structured draft quickly, especially when you provide customer notes, product details, and examples.', '$0–$50 for a portfolio page, domain, or basic writing tools.', 'Beginner to Intermediate', '$100–$750 per article or monthly retainers around $500–$2,000 for consistent work.', ['Pick one niche you understand.', 'Publish two sample articles that show your editing quality.', 'Pitch businesses with a specific content idea instead of a generic writing offer.']), idea('Etsy listing and product description service', 'Makers and small ecommerce sellers with good products but weak descriptions.', 'Improve product titles, descriptions, FAQs, personalization instructions, and customer message templates.', 'ChatGPT can generate multiple description angles and keyword-friendly variations, but you still verify product claims and brand voice.', '$0–$30 to start with a marketplace profile and sample listings.', 'Beginner', '$15–$75 per listing or $150–$500 for a small shop refresh.', ['Rewrite five sample listings in a clear niche.', 'Contact small shops with one helpful suggestion.', 'Package the service by number of listings to keep scope simple.'])] },
  canva: { ideas: [idea('Social media template packs', 'Creators, coaches, and local businesses that need consistent posts without hiring a designer.', 'Design reusable Instagram, Pinterest, LinkedIn, or Facebook templates and sell them as digital products or client packages.', 'Canva makes templates easy for non-designers to edit, which increases the value of the files you deliver.', '$0–$20 to start; Canva Pro can help with brand kits and premium assets.', 'Beginner', '$10–$49 per template pack or $150–$600 for custom branded sets.', ['Choose one platform and audience.', 'Build a 20-template sample pack.', 'Sell through your own site, Etsy, or direct outreach.']), idea('Branding starter kits', 'New freelancers and small businesses that need a basic visual identity.', 'Create logo concepts, color palettes, font pairings, business cards, and social banners.', 'Canva speeds up practical brand asset creation and handoff because clients can update files themselves.', '$0–$50 for a portfolio, mockups, and optional Canva Pro.', 'Beginner to Intermediate', '$200–$1,000 per starter kit depending on strategy depth and revisions.', ['Create three sample brand kits.', 'Define clear revision limits.', 'Offer a simple intake form for style preferences.']), idea('Printable and worksheet products', 'Teachers, parents, coaches, and planners buying low-cost downloadable resources.', 'Create planners, checklists, worksheets, classroom posters, and printable organizers.', 'Canva is useful because it combines layouts, icons, typography, and PDF export in one beginner-friendly workspace.', '$0–$30 plus marketplace fees if you sell on Etsy or similar platforms.', 'Beginner', '$3–$20 per product; income depends on traffic, quality, and catalog size.', ['Research a narrow use case.', 'Make one polished product with clear preview images.', 'Improve based on buyer questions before expanding the catalog.'])] },
  shopify: { ideas: [idea('Niche ecommerce store setup service', 'Local businesses and creators who want to sell online but do not want to configure a store themselves.', 'Set up Shopify themes, product pages, checkout settings, shipping basics, and launch checklists.', 'Shopify gives you the store infrastructure, so your value is helping clients organize products and launch correctly.', '$50–$200 for a portfolio, test store time, and basic business setup.', 'Beginner to Intermediate', '$500–$3,000 per setup depending on catalog size and customization.', ['Build a demo store in one niche.', 'Create a launch checklist.', 'Pitch businesses that already sell through social media or in person.']), idea('Digital product storefront', 'Creators with templates, downloads, courses, or files to sell.', 'Package and sell digital products such as templates, guides, presets, or worksheets through a branded storefront.', 'Shopify handles product pages, checkout, discount codes, and order delivery integrations for a small online business.', '$39/month and any app costs after trial or current plan changes.', 'Beginner', '$5–$100 per sale; results depend on product-market fit and traffic.', ['Validate one product with an audience first.', 'Create a simple storefront and email capture.', 'Drive traffic through content or a small existing audience.']), idea('Print-on-demand product testing', 'Designers or creators who want to test physical products without holding inventory.', 'Connect a print-on-demand app, upload designs, and test products like shirts, mugs, or posters.', 'Shopify provides the storefront while POD partners handle production and fulfillment; you focus on designs and marketing.', '$50–$150/month including Shopify, samples, and app costs.', 'Intermediate', '$5–$20 gross margin per sale is common before advertising costs.', ['Order samples before selling.', 'Start with a small product line.', 'Track margins carefully before scaling ads.'])] },
};

function idea(title: string, who: string, what: string, helps: string, cost: string, difficulty: SideHustleIdea['difficulty'], income: string, steps: string[]): SideHustleIdea { return { title, who, what, helps, cost, difficulty, income, steps }; }
function genericSideHustleProfile(product: Product): SideHustleProfile {
  const feature = product.features[0]?.title?.toLowerCase() ?? 'core workflow';
  const best = bestForText(product).toLowerCase();
  const useCase = product.useCases?.[0]?.toLowerCase() ?? feature;
  const category = (product.primaryCategory ?? product.category ?? product.categoryBadge ?? '').toLowerCase();
  const isCreative = /image|video|design|voice|audio|content|writing|marketing/.test(category + best + useCase);
  const isDev = /developer|coding|website|app|automation|builder/.test(category + best + useCase);
  const ideas = isDev ? [
    idea(`${product.name} implementation service`, `Small businesses that need ${feature} but do not have technical help.`, `Set up practical workflows, templates, integrations, or simple client deliverables around ${product.name}.`, `${product.name} is useful because it reduces setup time and gives you a repeatable workflow you can adapt for each client instead of starting from scratch.`, '$0–$100 to start, plus the tool subscription if the client does not provide access.', 'Beginner to Intermediate', '$300–$2,500 per project depending on complexity, revisions, and support.', ['Build one demo project.', 'Document a fixed launch checklist.', 'Sell a narrow package before offering custom work.']),
    idea('Prototype and MVP support', 'Founders who need a working proof of concept before hiring a full team.', `Create simple prototypes, landing pages, automations, or technical drafts using ${product.name}.`, `${product.name} helps you move faster from idea to usable draft, while your judgment keeps scope realistic and client expectations clear.`, '$50–$200 for hosting, domains, and testing accounts.', 'Intermediate', '$500–$5,000 per prototype depending on scope and handoff needs.', ['Pick a common founder problem.', 'Create two demo prototypes.', 'Use clear disclaimers about what is production-ready.']),
    idea('Workflow cleanup retainers', 'Teams already using the tool but not getting consistent results.', `Audit prompts, templates, workflows, or project structure and improve how the team uses ${product.name}.`, `${product.name} becomes more valuable when someone standardizes inputs, naming, review steps, and output quality checks.`, '$0–$100 to start if you can demonstrate the workflow.', 'Intermediate', '$300–$1,500/month for light support retainers.', ['Create an audit checklist.', 'Offer a one-time workflow review.', 'Convert satisfied clients into monthly support.'])
  ] : [
    idea(`${product.name} freelance service package`, `Freelancers and small businesses that need help with ${useCase}.`, `Use ${product.name} to create client-ready drafts, assets, reports, or campaign materials, then refine them before delivery.`, `${product.name} helps by speeding up the production work while you provide taste, strategy, fact-checking, and client communication.`, '$0–$100 to start, depending on whether you need a paid plan, portfolio site, or samples.', isCreative ? 'Beginner' : 'Beginner to Intermediate', '$100–$1,500 per project depending on deliverables and niche.', ['Choose one narrow client type.', `Create three samples made with ${product.name}.`, 'Offer a fixed-scope starter package.']),
    idea('Digital product templates', 'Creators who can package repeatable files, prompts, designs, lessons, or workflows.', `Turn repeatable ${product.name} workflows into templates, guides, presets, or downloadable resources.`, `${product.name} is useful for producing consistent assets and examples that buyers can adapt to their own work.`, '$0–$75 for the tool, marketplace fees, and product mockups.', 'Beginner', '$5–$99 per sale; meaningful income usually requires a focused audience or catalog.', ['Research one painful repeated task.', 'Build a small template pack.', 'Publish clear examples of the finished output.']),
    idea('Monthly content or operations support', 'Businesses that want recurring help instead of one-off projects.', `Provide a monthly service using ${product.name} for recurring ${feature}, reporting, content, or workflow tasks.`, `${product.name} helps you standardize recurring production so each month is easier to manage without lowering review quality.`, '$0–$150/month for software and basic business tools.', 'Intermediate', '$300–$2,000/month per client depending on workload and deliverables.', ['Define a monthly deliverable list.', 'Price around time and revision limits.', 'Start with one client and refine the process.'])
  ];
  return { intro: `${product.name} can support a realistic freelance business, digital products, or a small online business when you use it for work the tool is actually built to do. The best side hustles using ${product.name} usually combine the software’s ${feature} capabilities with your editing, judgment, and client communication.`, ideas, snapshot: { beginner: isCreative ? '⭐⭐⭐⭐⭐' : '⭐⭐⭐⭐☆', cost: 'Low', time: '1 Week', scalability: '⭐⭐⭐⭐☆', bestFor: isDev ? 'Developers / Freelancers / Agencies' : 'Freelancers / Creators / Agencies' }, relatedIntro: `If you are learning how to make money with ${product.name}, these related AI tools can help with planning, production, marketing, or client delivery:` };
}
function getSideHustleProfile(product: Product): SideHustleProfile { const base = genericSideHustleProfile(product); const override = sideHustleProfiles[product.slug] ?? {}; return { ...base, ...override, snapshot: { ...base.snapshot, ...override.snapshot }, ideas: override.ideas ?? base.ideas }; }

type NamedItem = { title: string; description: string };
type ExpandedFeature = { title: string; description?: string; whatItDoes?: string; whyItMatters?: string; whoBenefits?: string | string[]; bestFor?: string[]; example?: string; tradeoff?: string; recommendedWorkflow?: string; icon?: string };
type ExpandedUseCase = { title: string; scenario: string; problem: string; solution: string; outcome: string };
type Alternative = { name: string; slug?: string; logo?: string; description: string };
type ComparisonMatrix = { columns: string[]; rows: { feature: string; values: string[] }[] };
type SideHustleIdea = { title: string; who: string; what: string; helps: string; cost: string; difficulty: 'Beginner' | 'Beginner to Intermediate' | 'Intermediate'; income: string; steps: string[] };
type SideHustleProfile = { intro: string; ideas: SideHustleIdea[]; snapshot: { beginner: string; cost: string; time: string; scalability: string; bestFor: string }; relatedIntro: string };

function bestForText(product: Product) { return Array.isArray(product.bestFor) ? product.bestFor.join(', ') : product.bestFor; }
function sentence(value: string) { return value.trim().replace(/[.!?]?$/, '.'); }
function asTextList(value?: string | string[]) { if (!value) return ''; return Array.isArray(value) ? value.join(', ') : value; }
function editorialFeatures(product: Product): ExpandedFeature[] {
  const graph = product.knowledgeGraph?.facts.features ?? [];
  const base = product.features;
  return base.map((feature) => {
    const graphFeature = graph.find((item) => item.name.toLowerCase() === feature.title.toLowerCase());
    const example = graphFeature?.example ?? feature.example;
    return {
      ...feature,
      title: feature.title,
      description: feature.description,
      whatItDoes: graphFeature?.whatItDoes ?? feature.whatItDoes ?? feature.description,
      whyItMatters: graphFeature?.whyItMatters ?? feature.whyItMatters,
      whoBenefits: graphFeature?.bestFor ?? feature.whoBenefits,
      example,
      tradeoff: graphFeature?.tradeoff ?? feature.tradeoff,
      recommendedWorkflow: graphFeature?.recommendedWorkflow ?? feature.recommendedWorkflow ?? (example ? `Start with a real work packet, ask ${product.name} for a first-pass read, then verify the output before it becomes client, legal, financial, or production material.` : undefined),
    };
  });
}
function editorialUseCases(product: Product): ExpandedUseCase[] {
  const graphCases = product.knowledgeGraph?.facts.useCases ?? [];
  if (graphCases.length > 0) {
    return graphCases.map((item) => ({
      title: item.title,
      scenario: item.industry ? `${item.industry} team handling ${item.title.toLowerCase()}.` : `Team handling ${item.title.toLowerCase()}.`,
      problem: item.difficulty ? `The work is ${item.difficulty.toLowerCase()} enough that a shallow prompt can miss context, risks, or the next practical step.` : 'The work requires turning messy inputs into a decision-ready starting point.',
      solution: item.workflow,
      outcome: item.timeSaved ? `Expected outcome: ${sentence(item.timeSaved)} The human reviewer can spend more time judging the result instead of assembling the first pass.` : 'Expected outcome: a clearer first draft, review checklist, or analyst outline that still receives human review before use.',
    }));
  }
  return (product.useCases ?? []).map((item) => ({ title: item, scenario: item, problem: 'The starting material is scattered, incomplete, or too time-consuming to organize manually.', solution: sentence(item), outcome: 'Expected outcome: a more structured working draft that a subject-matter expert can refine.' }));
}

export function ProductTemplate({ product, relatedProducts }: { product: Product; relatedProducts?: Product[] }) {
  const quickFacts = product.quickFacts ?? [
    { label: 'Setup Time', value: product.setupTime },
    { label: 'Pricing', value: getPricingText(product) },
    { label: 'Platforms', value: product.platforms.join(', ') },
    { label: 'Best For', value: bestForText(product) },
    { label: 'Overall Rating', value: `${product.rating} / 5` },
  ];
  const jsonLdSchemas = buildProductReviewJsonLd(product);

  const showScreenshotGallery = shouldShowScreenshotGallery(product);

  return <main className="min-h-screen overflow-hidden bg-radial-blue pb-20 md:pb-0">
    {jsonLdSchemas.map((schema) => <script key={String(schema['@type'])} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    <Navbar product={product} />
    <Hero product={product} showHeaderImage={showScreenshotGallery} />
    {!showScreenshotGallery && <ReviewHeroImage product={product} />}
    <AffiliateDisclosure />
    <Section id="quick-facts" eyebrow="Quick facts" title={`${product.name} at a glance`}><FactGrid items={quickFacts} /></Section>
    <Section id="overview" eyebrow="Overview" title={`What is ${product.name}?`}><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-5 text-lg leading-8 text-slate-300">{(product.overview ?? [product.description]).map((p) => <p key={p}>{p}</p>)}</div><VerdictMini product={product} /></div></Section>
    {showScreenshotGallery && <ScreenshotGallery product={product} />}
    <Section id="features" eyebrow="Features" title="How the key features work in practice"><div className="grid gap-5 lg:grid-cols-2">{editorialFeatures(product).map((feature) => { const Icon = icons[feature.icon as keyof typeof icons] ?? Bot; return <Card key={feature.title}><Icon className="mb-5 h-6 w-6 text-blue-300" /><h3 className="text-2xl font-semibold text-white">{feature.title}</h3><FeatureDetail label="What it does" value={feature.whatItDoes ?? feature.description} /><FeatureDetail label="Why it matters" value={feature.whyItMatters} /><FeatureDetail label="Who benefits most" value={asTextList(feature.whoBenefits)} /><FeatureDetail label="Real-world example" value={feature.example} /><FeatureDetail label="Tradeoff or limitation" value={feature.tradeoff} /><FeatureDetail label="Recommended workflow" value={feature.recommendedWorkflow} /></Card>; })}</div><CenterCta href={product.affiliateLink}>Try {product.name} after comparing features</CenterCta></Section>
    <Section eyebrow="Pros & Cons" title={`A balanced ${product.name} review`}><div className="grid gap-6 lg:grid-cols-2"><ListCard title="Pros" items={product.pros} tone="pro" /><ListCard title="Cons" items={product.cons} tone="con" /></div></Section>
    <Section eyebrow="Editorial rating" title={`${product.name} rating breakdown`}><RatingBreakdown product={product} /></Section>
    <Section id="pricing" eyebrow="Pricing" title={`${product.name} pricing plans`}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{product.pricingPlans.map((plan) => <Card key={plan.name}><h3 className="text-2xl font-semibold">{plan.name}</h3><p className="mt-2 text-3xl font-bold text-white">{plan.price}</p><p className="mt-3 text-sm text-slate-300">{plan.description}</p><ul className="my-6 space-y-3">{plan.features.map((item) => <li key={item} className="flex gap-2 text-sm text-slate-200"><Check className="h-5 w-5 shrink-0 text-blue-300" />{item}</li>)}</ul><AffiliateButton href={product.affiliateLink}>{plan.cta}</AffiliateButton></Card>)}</div></Section>
    <Section eyebrow="Best fit" title={`Who should use ${product.name}`}><CardGrid items={product.audiences} /></Section>
    <Section eyebrow="Not a fit" title={`Who should skip ${product.name}`}><CardGrid items={product.notFor} warning /></Section>
    <Section eyebrow="Use cases" title={`Real-world ways to use ${product.name}`}><div className="grid gap-5 lg:grid-cols-2">{editorialUseCases(product).map((item) => <Card key={item.title}><SparkLabel>{item.title}</SparkLabel><UseCaseDetail label="Scenario" value={item.scenario} /><UseCaseDetail label="Problem" value={item.problem} /><UseCaseDetail label={`How ${product.name} solves it`} value={item.solution} /><UseCaseDetail label="Expected outcome" value={item.outcome} /></Card>)}</div></Section>
    <Section id="alternatives" eyebrow="Alternatives" title={`${product.name} alternatives to compare`}><Alternatives items={product.alternatives ?? []} /></Section>
    <Section id="comparison" eyebrow="Comparison" title={`${product.name} comparison table`}><Comparison matrix={product.comparisonMatrix} productName={product.name} /></Section>
    <Section id="faq" eyebrow="FAQ" title="Frequently asked questions"><div className="mx-auto max-w-3xl space-y-3">{product.faq.map((item) => <details key={item.question} className="glass group rounded-2xl p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-white">{item.question}<ChevronDown className="h-5 w-5 shrink-0 transition group-open:rotate-180" /></summary><p className="mt-4 text-slate-300">{item.answer}</p></details>)}</div></Section>
    <BusinessBuilder product={product} relatedProducts={relatedProducts ?? []} />
    <Section eyebrow="Final verdict" title={`Should you use ${product.name} in 2026?`}><Verdict product={product} /></Section>
    <CompareWith product={product} relatedProducts={relatedProducts ?? []} />
    <RelatedReviews product={product} relatedProducts={relatedProducts ?? []} />
    <Footer product={product} />
    <FloatingCta href={product.affiliateLink} productName={product.name} />
  </main>;
}

function Navbar({ product }: { product: Product }) { return <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-slate-950/70 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3 font-semibold" aria-label="AI Tool Hub home"><ProductLogo logo={product.logo} name={product.name} size={32} className="rounded-lg" />{product.name}</Link><div className="hidden gap-6 text-sm text-slate-300 md:flex"><Link href="/">Home</Link><a href="#features">Features</a><a href="#comparison">Compare</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div><AffiliateButton href={product.affiliateLink}>Try Now</AffiliateButton></div></nav>; }
function productHeroAlt(product: Product) { return product.heroImageAlt ?? `${product.name} application screenshot`; }
function Hero({ product, showHeaderImage }: { product: Product; showHeaderImage: boolean }) { return <section className={`mx-auto grid max-w-7xl items-center gap-12 px-6 pb-12 pt-32 lg:px-8 lg:pt-40 ${showHeaderImage ? 'lg:grid-cols-2' : ''}`}><div className={showHeaderImage ? '' : 'max-w-4xl'}><div className="mb-6 inline-flex items-center gap-3 rounded-full border border-blue-300/20 bg-blue-400/10 px-4 py-2 text-sm font-semibold text-blue-200"><ProductLogo logo={product.logo} name={product.name} size={24} className="rounded-md" />{product.categoryBadge ?? 'AI Assistant'}</div><h1 className="text-5xl font-bold tracking-tight text-white sm:text-7xl">{product.review.title}</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-slate-300">{product.tagline}.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><AffiliateButton href={product.affiliateLink}>Try {product.name}</AffiliateButton><a href="#overview" className="rounded-full border border-white/15 px-6 py-3 text-center font-semibold text-white transition hover:border-blue-300/50">Read Full Review</a></div></div>{showHeaderImage && <div className="glass rounded-[2rem] p-3 shadow-2xl shadow-blue-950/40"><ScreenshotImage src={product.heroImage} alt={productHeroAlt(product)} width={1600} height={1000} className="rounded-[1.5rem] border border-white/10" priority /></div>}</section>; }
function ReviewHeroImage({ product }: { product: Product }) { return <section className="mx-auto max-w-7xl px-6 pb-12 lg:px-8"><div className="glass overflow-hidden rounded-[2rem] p-3 shadow-2xl shadow-blue-950/30"><ScreenshotImage src={product.heroImage} alt={productHeroAlt(product)} width={1600} height={1000} sizes="(min-width: 1280px) 1200px, 100vw" className="rounded-[1.5rem] border border-white/10" /></div></section>; }
function ScreenshotGallery({ product }: { product: Product }) { if (!product.screenshots?.length) return null; return <Section id="screenshots" eyebrow="Screenshots" title={`${product.name} product gallery`}><div className="grid gap-5 md:grid-cols-2">{product.screenshots.map((screenshot, index) => <figure key={screenshot} className="glass overflow-hidden rounded-[2rem] p-3"><ScreenshotImage src={screenshot} alt={index === 0 && screenshot === product.heroImage ? productHeroAlt(product) : `${product.name} screenshot ${index + 1}`} width={1600} height={1000} sizes="(min-width: 768px) 50vw, 100vw" className="rounded-[1.5rem] border border-white/10" /><figcaption className="px-3 py-4 text-sm font-medium text-slate-300">{screenshotCaption(product, screenshot, index)}</figcaption></figure>)}</div></Section>; }
function screenshotCaption(product: Product, screenshot: string, index: number) { const captions: Record<string, string> = { dashboard: 'Dashboard: central BlueFX workspace for launching campaign workflows.', 'winning-ads': 'Winning Ads Finder: research placeholder for hooks, angles, and ad inspiration.', 'video-analyzer': 'Video Analyzer: review placeholder for pacing, structure, and creative improvements.', avatar: 'AI Avatar: presenter-style video creation placeholder.', thumbnail: 'Thumbnail Generator: concept board placeholder for testing social and video thumbnails.', pricing: 'Pricing: $1 trial and $37/month Founding Plan review placeholder.' }; const key = Object.keys(captions).find((item) => screenshot.includes(item)); return key ? captions[key] : `${product.name} screenshot ${index + 1}`; }
function Section({ id, eyebrow, title, children }: { id?: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[.3em] text-blue-300">{eyebrow}</p><h2 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-5xl">{title}</h2><div className="mt-10">{children}</div></section>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="glass rounded-3xl p-6">{children}</div>; }
function FactGrid({ items }: { items: { label: string; value: string }[] }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Card key={item.label}><p className="text-sm font-semibold uppercase tracking-[.2em] text-blue-300">{item.label}</p><p className="mt-3 text-2xl font-bold text-white">{item.value}</p></Card>)}</div>; }
function ListCard({ title, items, tone }: { title: string; items: string[]; tone: 'pro' | 'con' }) { return <Card><h3 className="text-2xl font-semibold">{title}</h3><ul className="mt-6 space-y-4">{items.map((item) => <li key={item} className="flex gap-3 text-slate-200">{tone === 'pro' ? <Check className="h-6 w-6 shrink-0 text-emerald-300" /> : <AlertTriangle className="h-6 w-6 shrink-0 text-amber-300" />}{item}</li>)}</ul></Card>; }
function FeatureDetail({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-200">{label}</p><p className="mt-2 leading-7 text-slate-300">{value}</p></div>; }
function UseCaseDetail({ label, value }: { label: string; value: string }) { return <div className="mt-4"><p className="text-sm font-semibold text-blue-200">{label}</p><p className="mt-1 leading-7 text-slate-300">{value}</p></div>; }
function CardGrid({ items, warning }: { items: NamedItem[]; warning?: boolean }) { return <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{items.map((item) => <Card key={item.title}>{warning && <XCircle className="mb-5 h-6 w-6 text-amber-300" />}<h3 className="text-xl font-semibold">{item.title}</h3><p className="mt-3 text-slate-300">{item.description}</p></Card>)}</div>; }



function BusinessBuilder({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) {
  const plan = enhancementPlan(product);
  return <>
    {plan.primary === 'classroom' && <ClassroomIdeas product={product} />}
    {plan.primary === 'projects' && <ProjectsYouCanBuild product={product} relatedProducts={relatedProducts} />}
    {plan.primary === 'marketing' && <MarketingWorkflows product={product} relatedProducts={relatedProducts} />}
    {plan.primary === 'content' && <ContentCreationIdeas product={product} relatedProducts={relatedProducts} />}
    {plan.primary === 'productivity' && <ProductivityWorkflows product={product} />}
    {plan.primary === 'business' && <BusinessUseCases product={product} />}
    {plan.includeSideHustles && <SideHustleIdeas product={product} relatedProducts={relatedProducts} />}
    {plan.includeBusinessStacks && <BusinessStacks product={product} relatedProducts={relatedProducts} />}
    <WorksBetterWith product={product} relatedProducts={relatedProducts} />
    <StarterStack product={product} relatedProducts={relatedProducts} />
    <UpgradePath product={product} />
    <BestBusinessFits product={product} />
  </>;
}

type EnhancementPrimary = 'classroom' | 'projects' | 'marketing' | 'content' | 'productivity' | 'business' | 'general';
type EnhancementPlan = { category: string; primary: EnhancementPrimary; includeSideHustles: boolean; includeBusinessStacks: boolean };
function productContext(product: Product) { return `${product.slug} ${product.name} ${product.category ?? ''} ${product.primaryCategory ?? ''} ${product.categoryBadge ?? ''} ${product.categories?.join(' ') ?? ''} ${product.tags?.join(' ') ?? ''} ${bestForText(product)} ${product.description} ${product.useCases?.join(' ') ?? ''}`.toLowerCase(); }
function enhancementPlan(product: Product): EnhancementPlan {
  const text = productContext(product);
  if (/lesson|teacher|student|classroom|education|school|ell|special education/.test(text)) return { category: 'Education', primary: 'classroom', includeSideHustles: false, includeBusinessStacks: false };
  if (/github|copilot|cursor|replit|bolt|lovable|developer|coding|code|app builder|website builder|webflow|hostinger/.test(text)) return { category: 'Developer Tools', primary: 'projects', includeSideHustles: /replit|bolt|lovable|webflow|hostinger|website/.test(text), includeBusinessStacks: true };
  if (/mailerlite|brevo|convertkit|hubspot|seo|semrush|surfer|email marketing|marketing platform|campaign/.test(text)) return { category: 'Marketing', primary: 'marketing', includeSideHustles: /copy|writing|seo/.test(text), includeBusinessStacks: true };
  if (/heygen|synthesia|runway|pictory|capcut|descript|video|voice|audio|elevenlabs|image generator|midjourney|leonardo|canva|design|presentation|content creation/.test(text)) return { category: 'Creative Tools', primary: 'content', includeSideHustles: true, includeBusinessStacks: true };
  if (/notion|clickup|motion|productivity|workspace|project management|notes/.test(text)) return { category: 'Productivity', primary: 'productivity', includeSideHustles: false, includeBusinessStacks: false };
  if (/crm|sales|operations|analytics|business intelligence|enterprise|monday/.test(text)) return { category: 'Business Software', primary: 'business', includeSideHustles: false, includeBusinessStacks: false };
  if (/shopify|ecommerce|commerce|store/.test(text)) return { category: 'Ecommerce', primary: 'business', includeSideHustles: true, includeBusinessStacks: true };
  return { category: product.categoryBadge ?? 'Software', primary: 'general', includeSideHustles: false, includeBusinessStacks: false };
}

type WorkflowCard = { title: string; icon: React.ReactNode; details: { label: string; value: string }[]; steps?: string[] };
function WorkflowGrid({ cards }: { cards: WorkflowCard[] }) { return <div className="grid gap-5 lg:grid-cols-3">{cards.map((card) => <Card key={card.title}><div className="mb-5 text-blue-300">{card.icon}</div><h3 className="text-2xl font-semibold text-white">{card.title}</h3>{card.details.map((detail) => <UseCaseDetail key={detail.label} label={detail.label} value={detail.value} />)}{card.steps && <div className="mt-5 border-t border-white/10 pt-4"><p className="text-sm font-semibold text-blue-200">Workflow steps</p><ol className="mt-2 list-decimal space-y-2 pl-5 text-slate-300">{card.steps.map((step) => <li key={step}>{step}</li>)}</ol></div>}</Card>)}</div>; }
function coreFeature(product: Product) { return product.features[0]?.title?.toLowerCase() ?? 'core workflow'; }
function ClassroomIdeas({ product }: { product: Product }) { const feature = coreFeature(product); return <Section id="classroom-teaching-ideas" eyebrow="Teaching workflows" title={`🎓 Classroom & Teaching Ideas for ${product.name}`}><WorkflowGrid cards={[{ title: 'Differentiated lesson prep', icon: <GraduationCap className="h-7 w-7" />, details: [{ label: 'Best for', value: 'Teachers adapting one objective for different readiness levels.' }, { label: `How ${product.name} helps`, value: `Use ${product.name} to draft lesson materials around ${feature}, then adjust wording, reading level, examples, and supports before students see it.` }, { label: 'Teacher check', value: 'Review standards alignment, factual accuracy, accommodations, and school policy before use.' }], steps: ['Paste the objective, source material, and learner needs.', 'Generate a core activity plus a simpler and more challenging version.', 'Add checks for understanding and a quick exit ticket.'] }, { title: 'Small-group intervention', icon: <Target className="h-7 w-7" />, details: [{ label: 'Best for', value: 'Reteaching after an exit ticket, quiz, or classroom observation.' }, { label: 'Workflow', value: 'Turn common mistakes into a short reteach prompt, guided practice, and independent practice set.' }, { label: 'Outcome', value: 'A faster planning loop for intervention without replacing teacher judgment.' }] }, { title: 'Assessment and feedback drafts', icon: <FileText className="h-7 w-7" />, details: [{ label: 'Best for', value: 'Rubrics, formative checks, homework review, and parent-friendly feedback language.' }, { label: 'Workflow', value: 'Start with real criteria, ask for aligned questions or feedback stems, then edit for tone and accuracy.' }, { label: 'Avoid', value: 'Do not upload sensitive student data unless your school policy and the tool terms allow it.' }] }]} /></Section>; }
function ProjectsYouCanBuild({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { const helper = stackTools(product, relatedProducts)[0]; return <Section id="projects-you-can-build" eyebrow="Build ideas" title={`🚀 Projects You Can Build With ${product.name}`}><WorkflowGrid cards={[{ title: 'Internal operations tool', icon: <Code className="h-7 w-7" />, details: [{ label: 'What to build', value: 'A small dashboard for requests, approvals, inventory, content calendars, or team handoffs.' }, { label: `How ${product.name} helps`, value: `${product.name} can speed up scaffolding, iteration, debugging, or deployment for a focused internal workflow.` }, { label: 'Pair it with', value: `${helper?.name ?? 'Notion'} for requirements, documentation, or handoff notes.` }] }, { title: 'Client landing page or portal', icon: <Rocket className="h-7 w-7" />, details: [{ label: 'What to build', value: 'A niche landing page, intake form, booking flow, or lightweight client portal.' }, { label: 'Good constraint', value: 'Keep the first version narrow: one audience, one workflow, one clear success metric.' }, { label: 'Quality check', value: 'Review generated code, accessibility, security-sensitive logic, and production configuration before launch.' }] }, { title: 'Portfolio automation', icon: <Zap className="h-7 w-7" />, details: [{ label: 'What to build', value: 'A Chrome extension, simple automation, API wrapper, or public demo that proves practical skill.' }, { label: 'Why it works', value: 'Small utilities are easier to finish, test, and explain than broad app ideas.' }, { label: 'Next step', value: 'Document the problem, screenshots, tradeoffs, and what you would improve next.' }] }]} /></Section>; }
function MarketingWorkflows({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { const helper = stackTools(product, relatedProducts)[0]; return <Section id="marketing-workflows" eyebrow="Marketing workflows" title={`📈 Marketing Workflows Using ${product.name}`}><WorkflowGrid cards={[{ title: 'Lead magnet follow-up', icon: <Mail className="h-7 w-7" />, details: [{ label: 'Goal', value: 'Turn a download, webinar, quiz, or signup into a helpful welcome sequence.' }, { label: `How ${product.name} helps`, value: `Use ${product.name} for the campaign step it handles best, then personalize segmentation, timing, and copy to the audience.` }, { label: 'Pairs well with', value: `${helper?.name ?? 'Canva'} for supporting assets, landing pages, or planning.` }], steps: ['Define the audience promise.', 'Create a short sequence with one job per email or touchpoint.', 'Measure opens, clicks, replies, and conversions before expanding.'] }, { title: 'SEO-to-email loop', icon: <Search className="h-7 w-7" />, details: [{ label: 'Goal', value: 'Convert educational content into subscribers and nurture them with related offers.' }, { label: 'Workflow', value: 'Research intent, publish useful content, add a relevant opt-in, and follow up with practical next steps.' }, { label: 'Avoid', value: 'Do not stuff keywords or send generic promotions that do not match the original search intent.' }] }, { title: 'Campaign optimization', icon: <ChartBar className="h-7 w-7" />, details: [{ label: 'Goal', value: 'Improve an existing funnel before buying more traffic.' }, { label: 'Workflow', value: 'Audit segments, subject lines, landing pages, and conversion points; test one variable at a time.' }, { label: 'Outcome', value: 'Cleaner attribution and better learning from each campaign cycle.' }] }]} /></Section>; }
function ContentCreationIdeas({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { const helper = stackTools(product, relatedProducts)[0]; return <Section id="content-creation-ideas" eyebrow="Creator workflows" title={`🎥 Content Creation Ideas for ${product.name}`}><WorkflowGrid cards={[{ title: 'Short-form content system', icon: <ImageIcon className="h-7 w-7" />, details: [{ label: 'Use case', value: 'TikTok, Reels, Shorts, Pinterest pins, or LinkedIn carousels built from one core idea.' }, { label: `How ${product.name} helps`, value: `${product.name} can produce the main creative asset or speed up editing, while you still guide hook, accuracy, brand voice, and final polish.` }, { label: 'Pair it with', value: `${helper?.name ?? 'ChatGPT'} for outlines, scripts, captions, or repurposing notes.` }] }, { title: 'Course and tutorial assets', icon: <FileText className="h-7 w-7" />, details: [{ label: 'Use case', value: 'Explainers, lesson visuals, walkthrough clips, worksheets, thumbnails, and presentation slides.' }, { label: 'Workflow', value: 'Start from a learning objective, create the smallest useful asset, then test whether viewers understand the next action.' }, { label: 'Avoid', value: 'Do not publish AI-generated visuals, voices, or clips without checking licensing, consent, and brand standards.' }] }, { title: 'Client content packages', icon: <BriefcaseBusiness className="h-7 w-7" />, details: [{ label: 'Use case', value: 'Monthly social graphics, ad variants, podcast clips, video explainers, or brand asset refreshes.' }, { label: 'Workflow', value: 'Create reusable intake questions, approval checkpoints, and revision limits so the tool speeds up delivery without lowering quality.' }, { label: 'Outcome', value: 'More consistent production for creators, local businesses, agencies, and marketing teams.' }] }]} /></Section>; }
function ProductivityWorkflows({ product }: { product: Product }) { return <Section id="productivity-workflows" eyebrow="Productivity workflows" title={`⚡ Productivity Workflows for ${product.name}`}><WorkflowGrid cards={[{ title: 'Weekly operating system', icon: <FolderKanban className="h-7 w-7" />, details: [{ label: 'Goal', value: 'Turn scattered tasks, notes, and projects into one reviewable weekly plan.' }, { label: 'Workflow', value: `Use ${product.name} to capture work, clarify next actions, and protect focus time.` }, { label: 'Best for', value: 'Founders, students, managers, freelancers, and knowledge workers.' }] }, { title: 'Meeting-to-action flow', icon: <Check className="h-7 w-7" />, details: [{ label: 'Goal', value: 'Prevent meeting notes from becoming forgotten context.' }, { label: 'Workflow', value: 'Capture decisions, owners, deadlines, and follow-up reminders in the same place you manage work.' }, { label: 'Outcome', value: 'Less manual status chasing and clearer accountability.' }] }, { title: 'Reusable templates', icon: <Lightbulb className="h-7 w-7" />, details: [{ label: 'Goal', value: 'Standardize recurring work such as content briefs, hiring steps, onboarding, or reports.' }, { label: 'Workflow', value: 'Build one template, use it for a real project, then refine fields based on what your team actually checks.' }, { label: 'Avoid', value: 'Do not overbuild dashboards before the workflow is proven.' }] }]} /></Section>; }
function BusinessUseCases({ product }: { product: Product }) { const feature = coreFeature(product); return <Section id="business-use-cases" eyebrow="Business use cases" title={`🏢 Business Use Cases for ${product.name}`}><WorkflowGrid cards={[{ title: 'Sales or customer pipeline', icon: <BriefcaseBusiness className="h-7 w-7" />, details: [{ label: 'Scenario', value: 'A small team needs a consistent way to track leads, customer requests, follow-ups, or renewals.' }, { label: `How ${product.name} helps`, value: `${product.name} supports the ${feature} workflow so managers can see status, owners, and next actions more clearly.` }, { label: 'Success metric', value: 'Fewer missed follow-ups and clearer ownership across the pipeline.' }] }, { title: 'Operations handoff', icon: <FolderKanban className="h-7 w-7" />, details: [{ label: 'Scenario', value: 'Work moves across sales, delivery, support, finance, or leadership.' }, { label: 'Workflow', value: 'Create shared views, approvals, automations, or reports that reduce manual status updates.' }, { label: 'Outcome', value: 'A more reliable handoff process without relying on scattered spreadsheets or chat threads.' }] }, { title: 'Management reporting', icon: <ChartBar className="h-7 w-7" />, details: [{ label: 'Scenario', value: 'Leaders need a practical view of workload, campaign progress, revenue activity, or team capacity.' }, { label: 'Workflow', value: 'Define the decisions the report supports first, then build only the fields and dashboards that answer those questions.' }, { label: 'Avoid', value: 'Do not treat dashboards as strategy; use them to trigger better decisions and follow-up.' }] }]} /></Section>; }

type Stack = { name: string; goal: string; tools: { name: string; slug?: string; contribution: string }[]; builder: string; buyers: string; complexity: string; ongoing: string };
function stackTools(product: Product, relatedProducts: Product[]) {
  const related = relatedProducts.filter((item) => item.slug !== product.slug).slice(0, 5);
  const fallback = defaultRelatedRecommendations.filter((item) => item.slug !== product.slug).slice(0, 5).map((item) => ({ name: item.slug.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' '), slug: item.slug }));
  return related.length >= 3 ? related.map((item) => ({ name: item.name, slug: item.slug })) : fallback;
}
function businessStacks(product: Product, relatedProducts: Product[]): Stack[] {
  const [a, b, c, d] = stackTools(product, relatedProducts);
  const feature = product.features[0]?.title?.toLowerCase() ?? 'core work';
  const useCase = product.bestFor?.[0] ?? product.useCases?.[0] ?? 'client work';
  return [
    { name: `${product.name} Client Delivery Stack`, goal: `Turn ${useCase.toLowerCase()} into a repeatable freelance service.`, tools: [{ name: product.name, slug: product.slug, contribution: `Produces or manages the main ${feature} workflow.` }, { ...a, contribution: 'Plans the brief, draft, or operating checklist.' }, { ...b, contribution: 'Creates supporting visuals, documents, campaigns, or client assets.' }], builder: 'Freelancers and consultants who want a narrow, fixed-scope offer.', buyers: 'Small businesses, creators, founders, or teams that need the outcome but not a full-time specialist.', complexity: 'Low to medium; the main work is packaging scope, examples, and revision rules.', ongoing: 'Client intake, production, review, revisions, delivery, and light reporting.' },
    { name: `${product.name} Content-to-Campaign Stack`, goal: `Create a practical content workflow with ${product.name} as the production anchor.`, tools: [{ name: product.name, slug: product.slug, contribution: `Handles the part of the workflow it is best at: ${feature}.` }, { ...c, contribution: 'Distributes, automates, sells, or organizes the finished work.' }, { ...a, contribution: 'Improves copy, planning, outlines, research, or QA before publishing.' }], builder: 'Creators, agencies, educators, or marketing teams building a repeatable publishing system.', buyers: 'Local businesses, ecommerce brands, educators, newsletters, or niche communities.', complexity: 'Medium; you need a calendar, approval process, and quality checks.', ongoing: 'Regular content planning, asset updates, scheduling, analytics review, and optimization.' },
    { name: `${product.name} Digital Product Stack`, goal: `Package knowledge, templates, media, or workflows into a small digital product offer.`, tools: [{ name: product.name, slug: product.slug, contribution: `Creates the core drafts, assets, store setup, code, analysis, or workflow pieces.` }, { ...b, contribution: 'Turns raw outputs into polished customer-facing materials.' }, { ...d, contribution: 'Supports selling, email follow-up, site building, automation, or project management.' }], builder: 'Solo creators and small teams who already understand a specific audience problem.', buyers: 'People who want templates, guides, assets, lessons, ecommerce products, or done-for-you setup help.', complexity: 'Medium; validation and support matter more than adding more tools.', ongoing: 'Customer feedback, updates, support emails, content marketing, and periodic product improvements.' },
  ];
}
function BusinessStacks({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { return <Section id="business-stack-ideas" eyebrow="Business stacks" title="🚀 Business Stack Ideas"><div className="grid gap-5 lg:grid-cols-3">{businessStacks(product, relatedProducts).map((stack) => <Card key={stack.name}><h3 className="text-2xl font-semibold text-white">{stack.name}</h3><UseCaseDetail label="Goal" value={stack.goal} /><div className="mt-5 space-y-3"><p className="text-sm font-semibold text-blue-200">Recommended tools</p>{stack.tools.map((tool) => <p key={`${stack.name}-${tool.name}`} className="text-slate-300"><strong className="text-white">{tool.name}</strong> — {tool.contribution}</p>)}</div><UseCaseDetail label="Who should build this stack" value={stack.builder} /><UseCaseDetail label="Who would buy these services" value={stack.buyers} /><UseCaseDetail label="Approximate startup complexity" value={stack.complexity} /><UseCaseDetail label="Expected ongoing work" value={stack.ongoing} /></Card>)}</div></Section>; }
function ToolLink({ tool }: { tool: { name: string; slug?: string } }) { return tool.slug ? <Link href={`/${tool.slug}`} className="font-semibold text-blue-200 hover:text-white">{tool.name}</Link> : <strong className="text-white">{tool.name}</strong>; }
function pairingReason(product: Product, tool: { name: string; slug?: string }) { const plan = enhancementPlan(product); const slug = tool.slug ?? ''; if (slug.includes('chatgpt') || slug.includes('claude')) return `Use ${tool.name} to turn rough ideas into briefs, outlines, QA checklists, or first-pass copy before producing the final work in ${product.name}.`; if (slug.includes('canva')) return `Use ${tool.name} for the visual layer: thumbnails, slides, social graphics, lead magnets, and client-facing assets that support the ${product.name} workflow.`; if (slug.includes('mailerlite') || slug.includes('brevo') || slug.includes('kit')) return `Use ${tool.name} when the ${product.name} output needs follow-up emails, nurture sequences, newsletters, or audience segmentation.`; if (slug.includes('notion')) return `Use ${tool.name} to organize briefs, approvals, reusable templates, client notes, and operating checklists around ${product.name}.`; if (slug.includes('shopify')) return `Use ${tool.name} when assets, copy, automations, or product ideas created with ${product.name} need a storefront and checkout path.`; if (slug.includes('replit') || slug.includes('cursor') || slug.includes('github')) return `Use ${tool.name} to build or maintain the technical pieces around ${product.name}, such as landing pages, internal tools, scripts, and integrations.`; if (plan.primary === 'classroom') return `${tool.name} can support planning, classroom materials, or organization around ${product.name} as long as student privacy and school policies are respected.`; if (plan.primary === 'projects') return `${tool.name} adds planning, design, marketing, or handoff support so ${product.name} projects are easier to explain, test, and deliver.`; if (plan.primary === 'content') return `${tool.name} helps extend ${product.name} into a complete content workflow from idea to asset to distribution.`; if (plan.primary === 'marketing') return `${tool.name} helps connect ${product.name} campaigns with stronger creative, copy, tracking, or follow-up.`; return `${tool.name} pairs with ${product.name} when you need supporting planning, production, delivery, or reporting around the core workflow.`; }
function WorksBetterWith({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { const related = stackTools(product, relatedProducts).slice(0, 6); return <Section id="works-better-with" eyebrow="Internal links" title="🔗 Works Even Better With"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{related.map((tool) => <Card key={tool.slug}><h3 className="text-xl font-semibold text-white"><ToolLink tool={tool} /></h3><p className="mt-3 text-slate-300">{pairingReason(product, tool)}</p></Card>)}</div></Section>; }
function bestFitLabels(product: Product) {
  const text = productContext(product);
  const labels = [
    ['Teachers', /education|teacher|lesson|student|classroom|school/.test(text)],
    ['Students', /student|study|learning|homework/.test(text) && !/teacher/.test(text)],
    ['Developers', /code|developer|github|cursor|replit|bolt|lovable|app builder/.test(text)],
    ['Creators', /video|audio|voice|image|design|content|creator|youtube|tiktok|canva|descript|runway|pictory|heygen/.test(text)],
    ['Freelancers', /writing|copy|design|video|website|seo|developer|automation|canva|chatgpt|claude|replit|lovable|hostinger|webflow/.test(text)],
    ['Small Business', /small business|shopify|ecommerce|website|crm|sales|operations|email marketing|marketing/.test(text)],
    ['Agencies', /agency|marketing|content|design|video|seo|website|automation|copy/.test(text)],
    ['Marketing Teams', /marketing|seo|email|campaign|copy|social|content|brevo|mailerlite|semrush|surfer/.test(text)],
    ['Designers', /design|image|graphics|canva|webflow|midjourney|leonardo/.test(text)],
    ['Ecommerce', /ecommerce|shopify|store|product|commerce/.test(text)],
  ] as const;
  return labels.filter(([, include]) => include).map(([label]) => label).slice(0, 8);
}
function BestBusinessFits({ product }: { product: Product }) { const fits = bestFitLabels(product); if (fits.length === 0) return null; return <Section id="best-business-fits" eyebrow="Best fit" title="🎯 Best Fit"><Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{fits.map((fit) => <p key={fit} className="flex items-center gap-3 text-slate-200"><Check className="h-5 w-5 text-emerald-300" />{fit}</p>)}</div></Card></Section>; }
function starterStackCopy(product: Product, tools: { name: string; slug?: string }[]) { const plan = enhancementPlan(product); const names = tools.map((tool) => tool.name).join(' + '); if (plan.primary === 'classroom') return `${names} is a practical beginner workflow for teaching because it keeps planning, differentiation, classroom assets, and review in a small stack instead of asking teachers to manage too many tools.`; if (plan.primary === 'projects') return `${names} is a practical beginner workflow for building because it covers the core build environment, planning, documentation, and the first layer of polish without overcomplicating the project.`; if (plan.primary === 'marketing') return `${names} is a practical beginner workflow for marketing because it connects campaign creation with assets, copy, follow-up, and organization before adding advanced automation.`; if (plan.primary === 'content') return `${names} is a practical beginner workflow for creators because it covers ideation, production, polish, and distribution support while keeping quality review human.`; if (plan.primary === 'productivity') return `${names} is a practical beginner workflow for productivity because it starts with capture, prioritization, templates, and weekly review before adding more dashboards.`; if (plan.primary === 'business') return `${names} is a practical beginner workflow for business teams because it keeps the focus on one operational process, clear ownership, and simple reporting.`; return `${names} is a sensible starter workflow with ${product.name} because it keeps the stack small and focused on planning, production, and delivery.`; }
function StarterStack({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { const tools = [{ name: product.name, slug: product.slug }, ...stackTools(product, relatedProducts).slice(0, 3)]; return <Section id="recommended-starter-stack" eyebrow="Starter stack" title="⭐ Recommended Starter Stack"><Card><div className="flex flex-wrap gap-3">{tools.map((tool) => <span key={tool.slug} className="rounded-full border border-white/15 px-4 py-2 text-slate-200">{tool.name}</span>)}</div><p className="mt-5 leading-7 text-slate-300">{starterStackCopy(product, tools)}</p></Card></Section>; }
function upgradeSteps(product: Product) { const plan = enhancementPlan(product); if (plan.primary === 'classroom') return [`Beginner: use ${product.name} for one lesson component such as bell ringers or exit tickets`, 'Intermediate: add differentiation, intervention groups, and rubric drafts', 'Advanced: standardize unit planning templates, assessment review, and teacher team collaboration']; if (plan.primary === 'projects') return [`Beginner: build one narrow prototype with ${product.name}`, 'Intermediate: add testing, documentation, deployment, and user feedback', 'Advanced: connect APIs, authentication, analytics, and maintainable handoff processes']; if (plan.primary === 'marketing') return [`Beginner: use ${product.name} for one campaign or sequence`, 'Intermediate: add segmentation, reusable creative assets, and one testing rhythm', 'Advanced: connect analytics, automation, sales handoff, and lifecycle campaigns']; if (plan.primary === 'content') return [`Beginner: create one repeatable content format with ${product.name}`, 'Intermediate: repurpose the same idea across channels with human review', 'Advanced: build a calendar, approval workflow, brand kit, and performance review loop']; if (plan.primary === 'productivity') return [`Beginner: use ${product.name} for capture and weekly planning`, 'Intermediate: add templates for recurring work and meeting follow-up', 'Advanced: connect team dashboards, automations, and quarterly review workflows']; if (plan.primary === 'business') return [`Beginner: map one business process inside ${product.name}`, 'Intermediate: add ownership, automations, and reporting views', 'Advanced: connect departments, governance, analytics, and executive review rhythms']; return [`Beginner: use ${product.name} for one narrow use case`, 'Intermediate: add supporting tools only after the workflow is repeatable', 'Advanced: document quality checks, handoffs, and optimization loops']; }
function UpgradePath({ product }: { product: Product }) { const steps = upgradeSteps(product); return <Section id="upgrade-path" eyebrow="Roadmap" title="📈 Upgrade Path"><Card><ol className="space-y-4">{steps.map((step, index) => <li key={step} className="flex gap-3 text-slate-200"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-400/20 text-sm font-bold text-blue-200">{index + 1}</span>{step}</li>)}</ol></Card></Section>; }


function SideHustleIdeas({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) {
  const profile = getSideHustleProfile(product);
  return <Section id="side-hustle-ideas" eyebrow="Side hustle ideas" title={`💰 Side Hustle Ideas Using ${product.name}`}><div className="max-w-4xl space-y-5 text-lg leading-8 text-slate-300"><p>{profile.intro}</p><p>{`These are practical business ideas using ${product.name}; results depend on skill, positioning, demand, and consistent delivery.`}</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2">{profile.ideas.map((item, index) => <Card key={item.title}><p className="text-sm font-semibold uppercase tracking-[.2em] text-blue-300">Side Hustle #{index + 1}</p><h3 className="mt-3 text-2xl font-semibold text-white">{item.title}</h3><SideHustleDetail label="Who this is for" value={item.who} /><SideHustleDetail label="What you'll do" value={item.what} /><SideHustleDetail label={`How ${product.name} helps`} value={item.helps} /><SideHustleDetail label="Startup cost" value={item.cost} /><SideHustleDetail label="Difficulty" value={item.difficulty} /><SideHustleDetail label="Potential customers" value={item.who} /><SideHustleDetail label="Why this tool is valuable" value={item.helps} /><div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-200">First steps</p><ol className="mt-2 list-decimal space-y-2 pl-5 text-slate-300">{item.steps.map((step) => <li key={step}>{step}</li>)}</ol></div></Card>)}</div><QuickSnapshot profile={profile} /></Section>;
}
function SideHustleDetail({ label, value }: { label: string; value: string }) { return <div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-semibold uppercase tracking-[.2em] text-blue-200">{label}</p><p className="mt-2 leading-7 text-slate-300">{value}</p></div>; }
function QuickSnapshot({ profile }: { profile: SideHustleProfile }) { const rows = [['Beginner Friendly', profile.snapshot.beginner], ['Startup Cost', profile.snapshot.cost], ['Time to First Client', profile.snapshot.time], ['Scalability', profile.snapshot.scalability], ['Best For', profile.snapshot.bestFor]]; return <div className="mt-10 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[560px] text-left"><thead className="bg-white/5 text-white"><tr><th className="px-5 py-4">Category</th><th className="px-5 py-4">Rating</th></tr></thead><tbody>{rows.map(([category, rating]) => <tr key={category} className="border-t border-white/10 text-slate-300"><th className="px-5 py-4 text-white">{category}</th><td className="px-5 py-4">{rating}</td></tr>)}</tbody></table></div>; }
function CompareWith({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { if (relatedProducts.length === 0) return null; return <Section eyebrow="Compare with" title={`Compare ${product.name} against similar tools`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{relatedProducts.map((tool) => <Link key={tool.slug} href={`/compare/${getComparisonSlug(product, tool)}`} className="glass rounded-3xl p-6 transition hover:border-blue-300/40"><ProductLogo logo={tool.logo} name={tool.name} size={40} className="rounded-xl" /><h3 className="mt-5 text-xl font-semibold text-white">{product.name} vs {tool.name}</h3><p className="mt-3 text-sm text-slate-300">Compare pricing, features, pros, cons, and best-fit users.</p><p className="mt-4 text-sm font-semibold text-blue-200">Compare Now →</p></Link>)}</div></Section>; }
function RelatedReviews({ product, relatedProducts }: { product: Product; relatedProducts: Product[] }) { if (relatedProducts.length === 0) return null; return <Section eyebrow="Related reviews" title={`More ${product.categoryBadge?.toLowerCase() ?? 'software'} reviews to compare`}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{relatedProducts.map((tool) => <Link key={tool.slug} href={`/${tool.slug}`} className="glass rounded-3xl p-6 transition hover:border-blue-300/40"><ProductLogo logo={tool.logo} name={tool.name} size={40} className="rounded-xl" /><h3 className="mt-5 text-xl font-semibold text-white">{tool.name}</h3><p className="mt-3 text-sm text-slate-300">{tool.tagline}</p><p className="mt-4 text-sm font-semibold text-blue-200">Read Review →</p></Link>)}</div></Section>; }
function Alternatives({ items }: { items: Alternative[] }) { return <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{items.map((item) => <Card key={item.name}><ProductLogo logo={item.logo} name={item.name} size={48} className="rounded-xl" /><h3 className="mt-5 text-xl font-semibold">{item.name}</h3><p className="mt-3 min-h-24 text-sm text-slate-300">{item.description}</p>{item.slug ? <Link href={`/${item.slug}`} className="mt-5 inline-flex rounded-full border border-white/15 px-4 py-2 text-sm font-semibold text-white">Read Review</Link> : <span className="mt-5 inline-flex rounded-full border border-white/10 px-4 py-2 text-sm font-semibold text-slate-300">Comparison only</span>}</Card>)}</div>; }
function Comparison({ matrix, productName }: { matrix?: ComparisonMatrix; productName: string }) { const columns = matrix?.columns ?? [productName]; const rows = matrix?.rows ?? []; return <div className="overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[760px] text-left"><thead className="bg-white/5 text-white"><tr>{['Feature', ...columns].map((h) => <th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.feature} className="border-t border-white/10 text-slate-300"><th className="px-5 py-4 text-white">{row.feature}</th>{columns.map((column, index) => <td key={`${row.feature}-${column}`} className="px-5 py-4">{row.values[index] ?? '—'}</td>)}</tr>)}</tbody></table></div>; }
function VerdictMini({ product }: { product: Product }) { return <div className="sticky top-28"><Card><div className="flex text-blue-300">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="h-5 w-5 fill-current" />)}</div><p className="mt-4 text-sm uppercase tracking-[.2em] text-blue-200">Overall Rating</p><p className="mt-2 text-3xl font-bold text-white">{product.rating}/5</p><p className="mt-4 text-sm uppercase tracking-[.2em] text-blue-200">Starting Price</p><p className="mt-2 text-white">{getPricingText(product)}</p><p className="mt-4 text-sm uppercase tracking-[.2em] text-blue-200">Free Trial</p><p className="mt-2 text-white">{typeof product.pricing === 'object' ? product.pricing.freePlan ?? 'Check current offer' : 'Check current offer'}</p><p className="mt-4 text-sm uppercase tracking-[.2em] text-blue-200">Best For</p><p className="mt-2 text-slate-300">{bestForText(product)}.</p><CenterCta href={product.affiliateLink}>Try {product.name} →</CenterCta></Card></div>; }
function RatingBreakdown({ product }: { product: Product }) { const ratings = [{ label: 'Ease of Use', value: product.ratings?.easeOfUse }, { label: 'Features', value: product.ratings?.features }, { label: 'AI Quality', value: product.ratings?.aiQuality }, { label: 'Templates', value: product.ratings?.integrations }, { label: 'Automation', value: product.ratings?.value }, { label: 'Pricing', value: product.ratings?.value }, { label: 'Support', value: product.ratings?.support }, { label: 'Overall', value: product.rating }]; return <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{ratings.map((item) => <Card key={item.label}><p className="text-sm font-semibold uppercase tracking-[.2em] text-blue-300">{item.label}</p><p className="mt-3 text-3xl font-bold text-white">{item.value?.toFixed(1) ?? '—'} / 5</p></Card>)}</div>; }
function Verdict({ product }: { product: Product }) { return <div className="glass rounded-[2rem] p-8 lg:p-10"><div className="grid gap-8 lg:grid-cols-[280px_1fr]"><div><p className="text-sm uppercase tracking-[.3em] text-blue-300">Overall Rating</p><p className="mt-3 text-6xl font-bold text-white">{product.rating}</p><p className="text-slate-300">out of 5</p></div><div><h3 className="text-3xl font-bold text-white">Our recommendation</h3><p className="mt-4 text-lg leading-8 text-slate-300">{product.verdict ?? product.review.summary}</p><p className="mt-4 text-slate-200"><strong>Best for:</strong> {bestForText(product)}.</p><div className="mt-8"><AffiliateButton href={product.affiliateLink}>Try {product.name} →</AffiliateButton></div></div></div></div>; }
function SparkLabel({ children }: { children: React.ReactNode }) { return <h3 className="text-xl font-semibold text-white">{children}</h3>; }
function CenterCta({ href, children }: { href: string; children: React.ReactNode }) { return <div className="mt-8 text-center"><AffiliateButton href={href}>{children}</AffiliateButton></div>; }
function AffiliateDisclosure() { return <section className="mx-auto max-w-7xl px-6 lg:px-8"><div className="glass rounded-3xl border border-blue-300/20 p-5 text-sm leading-6 text-slate-300"><strong className="text-white">Affiliate Disclosure</strong><p className="mt-2">If you purchase through links on this page, AIToolBet may earn a commission at no extra cost to you. Our reviews are based on product research and, whenever possible, hands-on testing.</p></div></section>; }
function Footer({ product }: { product: Product }) { return <footer className="border-t border-white/10 px-6 py-10 text-center text-sm text-slate-400">© {new Date().getFullYear()} {product.name} review. Affiliate disclosure: links may be sponsored.</footer>; }
