import type { Metadata } from 'next';
import Link from 'next/link';
import { getProductsByCategory, getProductHref, sortProducts } from '@/lib/products';
import { EDUCATION_AUDIENCES, EDUCATION_COMPARISONS, EDUCATION_GUIDES, guideSlug } from '@/lib/education';
export const metadata: Metadata = { title: 'Best Educational AI Software for Teachers & Schools', description: 'Compare educational AI tools for teachers, schools, administrators, students, and families with classroom-focused reviews, scorecards, guides, and comparisons.', alternates: { canonical: '/education-ai' } };
type Props={searchParams?:Promise<{audience?:string;sort?:string;q?:string}>};
export default async function EducationAI({searchParams}:Props){const p=await searchParams; const audience=p?.audience??'all'; const q=(p?.q??'').toLowerCase(); let tools=sortProducts(await getProductsByCategory('education'),p?.sort??'rating'); tools=tools.filter(t=>(audience==='all'||[t.users,...(t.bestFor instanceof Array?t.bestFor:[t.bestFor])].join(' ').toLowerCase().includes(audience.replace('schools','school').replace('teachers','teacher').replace('administrators','administrator'))) && (!q||[t.name,t.description,...(t.tags??[])].join(' ').toLowerCase().includes(q))); const top=tools.slice(0,3); const free=tools.filter(t=>JSON.stringify(t.pricing).toLowerCase().includes('free')).slice(0,4); return <main className="min-h-screen bg-radial-blue px-6 py-16 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.3em] text-blue-300">Educational AI</p><h1 className="mt-4 max-w-5xl text-5xl font-bold sm:text-7xl">AI software evaluated for real education workflows</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-slate-300">Independent, evidence-labeled reviews for teachers, schools, administrators, tutors, instructional designers, parents, and students. Compare instructional impact, adoption, privacy, accessibility, differentiation, and implementation—not feature lists alone.</p>
<form className="mt-10 grid gap-3 rounded-3xl border border-white/10 bg-white/5 p-5 md:grid-cols-[1fr_auto_auto]"><input name="q" defaultValue={p?.q} placeholder="Search educational tools and workflows" className="rounded-full bg-slate-950/70 px-5 py-3"/><select name="audience" defaultValue={audience} className="rounded-full bg-slate-950 px-5 py-3">{EDUCATION_AUDIENCES.map(a=><option key={a}>{a}</option>)}</select><button className="rounded-full bg-blue-500 px-6 py-3 font-bold">Filter tools</button></form>
<Section title="Featured and top-rated tools"><Cards tools={top}/></Section><Section title="All educational AI reviews"><Cards tools={tools}/></Section>{free.length>0&&<Section title="Free access to investigate"><Cards tools={free}/></Section>}
<Section title="Education comparisons"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{EDUCATION_COMPARISONS.filter(([a,b])=>tools.some(t=>t.slug===a)&&tools.some(t=>t.slug===b)).map(([a,b])=><Link className="rounded-2xl border border-white/10 bg-white/5 p-5" key={`${a}-${b}`} href={`/compare/${a}-vs-${b}`}>{tools.find(t=>t.slug===a)?.name} vs {tools.find(t=>t.slug===b)?.name} →</Link>)}</div></Section>
<Section title="Buying guides and teacher workflows"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{EDUCATION_GUIDES.map(g=><Link className="rounded-2xl border border-white/10 bg-white/5 p-5" key={g} href={`/education-ai/guides/${guideSlug(g)}`}>{g} →</Link>)}</div></Section></div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="py-12"><h2 className="mb-7 text-3xl font-bold">{title}</h2>{children}</section>}
function Cards({tools}:{tools:Awaited<ReturnType<typeof getProductsByCategory>>}){return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tools.map(t=><Link href={getProductHref(t)} key={t.slug} className="rounded-3xl border border-white/10 bg-white/5 p-6"><p className="text-sm text-blue-300">{t.categoryBadge}</p><h3 className="mt-2 text-2xl font-bold">{t.name}</h3><p className="mt-3 text-slate-300">{t.summary??t.description}</p><p className="mt-5 font-semibold">{t.rating}/5 · Read review →</p></Link>)}</div>}
