import type { Category, Product } from './products';

export type CategoryEditorial = {
  definition: string;
  audiences: string[];
  jobs: string[];
  mistake: string;
  beginner: string;
  professional: string;
  trend: string;
  differentiator: string;
  personas: string[];
};

const EDITORIAL: Record<string, CategoryEditorial> = {
  assistant: { definition: 'general-purpose systems that interpret natural-language requests and help with writing, analysis, planning, and everyday knowledge work', audiences: ['Solo professional', 'Student', 'Operations lead', 'Small business', 'Enterprise team'], jobs: ['turning rough questions into useful drafts', 'summarizing working material', 'planning repeatable tasks'], mistake: 'buying the model with the loudest launch rather than checking whether it handles your files, privacy needs, and recurring prompts', beginner: 'Start with a broad assistant that has a usable free tier and a clean interface; learn one repeatable prompt-and-review routine before adding specialist products.', professional: 'Power users should prioritize model reliability, workspace controls, connectors, long-context handling, and a documented process for verifying consequential output.', trend: 'Assistants are becoming action layers: they search connected sources, work across longer projects, and hand tasks to purpose-built tools rather than stopping at a chat response.', differentiator: 'the quality of the answer after your second and third follow-up, not the polish of the first demo', personas: ['New user', 'Researcher', 'Freelancer', 'Operations team', 'Enterprise buyer'] },
  writing: { definition: 'software that helps plan, draft, rewrite, optimize, and repurpose text while keeping a human editor in control', audiences: ['Freelance writer', 'Content marketer', 'Founder', 'Agency', 'Editorial team'], jobs: ['moving from brief to first draft', 'adapting one idea to several channels', 'tightening structure and voice'], mistake: 'measuring value by word count; undifferentiated copy creates an editing and fact-checking bill later', beginner: 'Choose a guided editor with templates and a free plan, then build a small voice guide from writing you would genuinely publish.', professional: 'Professional teams need shared style rules, approval stages, SEO or campaign integrations, version history, and predictable output at volume.', trend: 'The category is moving from one-shot generation toward source-grounded briefs, brand-memory systems, and multi-step editorial workflows.', differentiator: 'how much publishable judgment survives the first edit', personas: ['New writer', 'SEO specialist', 'Freelancer', 'Content agency', 'Marketing team'] },
  coding: { definition: 'developer software that explains code, completes functions, searches repositories, proposes edits, and increasingly executes multi-file engineering tasks', audiences: ['Learning developer', 'Independent maker', 'Product engineer', 'Engineering lead', 'Enterprise platform team'], jobs: ['understanding unfamiliar code', 'reducing repetitive implementation', 'finding and fixing defects'], mistake: 'accepting a plausible patch without tests, security review, or an understanding of what changed', beginner: 'Use a tool that explains suggestions and works inside a familiar editor; small, testable tasks are a better starting point than autonomous rewrites.', professional: 'Experienced teams should examine repository indexing, model choice, agent permissions, auditability, security posture, and usage-cost controls.', trend: 'Coding copilots are turning into agents that plan, edit, run commands, and respond to test failures, which makes guardrails more important than autocomplete speed.', differentiator: 'the percentage of proposed changes that survive review and CI', personas: ['Student developer', 'Indie hacker', 'Software engineer', 'Startup team', 'Enterprise engineering'] },
  research: { definition: 'tools for discovering sources, interrogating documents, synthesizing evidence, and turning a large reading list into a traceable analysis', audiences: ['Student', 'Analyst', 'Writer', 'Consultant', 'Research team'], jobs: ['finding a credible starting set of sources', 'extracting themes from documents', 'building an evidence-backed summary'], mistake: 'confusing a fluent synthesis with a supported conclusion or failing to open the cited source', beginner: 'Begin with a product that exposes citations beside its claims and test it on a topic where you already know the evidence.', professional: 'Serious research calls for source controls, document permissions, exportable notes, reproducible queries, and clear boundaries between quotations and inference.', trend: 'Research products are combining live retrieval, private document collections, and notebook-style artifacts so findings remain inspectable after a chat ends.', differentiator: 'the distance between an answer and the primary evidence needed to verify it', personas: ['Student researcher', 'Journalist', 'Consultant', 'Knowledge team', 'Enterprise analyst'] },
  education: { definition: 'teacher- and learner-facing software that supports lesson preparation, differentiation, assessment, tutoring, classroom activities, and school operations', audiences: ['New teacher', 'Instructional coach', 'School leader', 'Student support team', 'District buyer'], jobs: ['adapting materials for different learners', 'preparing instruction faster', 'creating useful checks for understanding'], mistake: 'choosing a long feature list before checking age suitability, accessibility, privacy, curriculum fit, and teacher oversight', beginner: 'Teachers should solve one weekly bottleneck first—such as a differentiated reading or exit ticket—and review every generated resource before class.', professional: 'Schools need rostering and LMS fit, administrative controls, procurement-ready privacy documentation, staff training, and a measured adoption plan.', trend: 'Educational AI is shifting from generic prompts to standards-aware planning, grounded classroom materials, and teacher-controlled personalization.', differentiator: 'whether it improves an actual instructional decision rather than merely producing more materials', personas: ['New teacher', 'Instructional coach', 'Principal', 'Student', 'District team'] },
  business: { definition: 'applications that use automation and AI to improve planning, customer work, operations, reporting, and decisions across a company', audiences: ['Founder', 'Operations manager', 'Sales team', 'Department lead', 'Enterprise buyer'], jobs: ['standardizing recurring processes', 'finding answers across business data', 'reducing administrative handoffs'], mistake: 'automating a broken process or purchasing overlapping seats without assigning an owner and success metric', beginner: 'Pick one high-frequency, low-risk process with an obvious before-and-after measure and run a short pilot with a small group.', professional: 'Mature buyers should evaluate identity management, permissions, integrations, data retention, audit logs, support, and total deployment cost.', trend: 'Business platforms are embedding assistants inside systems of record and adding agents that move work between applications with human approval.', differentiator: 'measurable throughput gained after implementation costs and review time are included', personas: ['Solo founder', 'Small business', 'Operations lead', 'Revenue team', 'Enterprise buyer'] },
  marketing: { definition: 'software that helps teams research audiences, develop campaigns, produce creative, distribute messages, and learn from performance data', audiences: ['Solo marketer', 'Creator', 'Growth team', 'Agency', 'Global brand'], jobs: ['moving from insight to campaign brief', 'producing channel-ready variants', 'connecting creative work to results'], mistake: 'scaling output before clarifying positioning, audience, measurement, and the approval standard for on-brand work', beginner: 'Start with a single channel and a tool whose templates match it; keep the message and offer human-owned while AI accelerates variants.', professional: 'Advanced teams need brand governance, asset and analytics integrations, collaboration, attribution fit, and repeatable review workflows.', trend: 'Marketing suites are connecting audience research, generation, personalization, and performance feedback instead of treating each as a separate prompt.', differentiator: 'the speed at which a team can produce a defensible test and learn from it', personas: ['New marketer', 'Creator', 'Growth lead', 'Agency', 'Marketing team'] },
  development: { definition: 'platforms for building, deploying, automating, and maintaining websites or applications, often with visual builders and AI-assisted generation', audiences: ['No-code beginner', 'Freelancer', 'Product builder', 'Development agency', 'Platform team'], jobs: ['prototyping an idea', 'shipping a maintainable application', 'operating releases and infrastructure'], mistake: 'optimizing for the fastest prototype while ignoring code ownership, portability, observability, accessibility, and the cost of production traffic', beginner: 'Choose a guided platform with sensible defaults, preview environments, and an escape route for custom code when the project grows.', professional: 'Professional evaluation should cover deployment controls, extensibility, collaboration, security, performance, monitoring, and predictable scaling.', trend: 'Natural-language building is merging with visual editing and code-aware agents, shortening prototyping while raising the bar for production review.', differentiator: 'how smoothly a promising prototype becomes an operable product', personas: ['No-code beginner', 'Indie maker', 'Developer', 'Agency', 'Platform team'] },
  productivity: { definition: 'tools that organize tasks, notes, documents, schedules, and team knowledge so less attention is lost to coordination', audiences: ['Student', 'Freelancer', 'Manager', 'Remote team', 'Operations team'], jobs: ['capturing information once', 'finding the next action', 'keeping shared work visible'], mistake: 'building an elaborate workspace before agreeing on the few habits and ownership rules that keep it current', beginner: 'Adopt the smallest system that reliably captures tasks and reference material; templates are useful only when they reduce decisions.', professional: 'Teams should test search, permissions, automations, integrations, reporting, offline access, and migration before consolidating critical work.', trend: 'Productivity products are adding meeting capture, workspace search, and agents that turn unstructured updates into assigned, trackable actions.', differentiator: 'whether the system still feels clear on a busy Friday afternoon', personas: ['Student', 'Freelancer', 'Team lead', 'Remote team', 'Operations manager'] },
  finance: { definition: 'software that assists with bookkeeping, forecasting, expense work, financial analysis, and the presentation of business or personal financial information', audiences: ['Independent professional', 'Bookkeeper', 'Finance manager', 'Founder', 'Enterprise finance team'], jobs: ['organizing financial inputs', 'spotting patterns and exceptions', 'preparing understandable reports'], mistake: 'treating generated analysis as financial advice or allowing automation to post consequential entries without reconciliation and review', beginner: 'Use automation first for categorization and reporting support, keep source records, and ask a qualified professional about consequential decisions.', professional: 'Finance teams need strong controls, audit trails, role-based access, data exports, integration reliability, and a clear human approval boundary.', trend: 'Financial tools are pairing conversational analysis with anomaly detection and workflow automation, while trustworthy provenance remains the real constraint.', differentiator: 'the clarity of the audit trail behind every important number', personas: ['Freelancer', 'Bookkeeper', 'Founder', 'Finance team', 'Enterprise controller'] },
  design: { definition: 'visual creation software for generating concepts, layouts, images, brand assets, presentations, and production-ready creative', audiences: ['Non-designer', 'Content creator', 'Brand designer', 'Creative agency', 'Marketing team'], jobs: ['turning a brief into visual directions', 'creating consistent campaign assets', 'adapting work across formats'], mistake: 'mistaking a polished template or first generation for a distinctive, accessible, legally usable final asset', beginner: 'Start with a template-led product that makes sizing and hierarchy easy, then learn to customize typography, color, and imagery deliberately.', professional: 'Creative teams should examine control, consistency, licensing, export quality, collaboration, brand systems, and interoperability with their core software.', trend: 'Design tools are combining generation with editable layers, reference-driven style control, and rapid resizing so ideation and production happen in one workspace.', differentiator: 'how much intentional control remains after the initial generation', personas: ['Non-designer', 'Creator', 'Brand designer', 'Agency', 'Creative team'] },
  'creator-tools': { definition: 'software that helps independent publishers and media teams plan, make, edit, package, distribute, and monetize digital content', audiences: ['New creator', 'Newsletter writer', 'Video producer', 'Podcast team', 'Media business'], jobs: ['turning one idea into a repeatable format', 'reducing editing and packaging time', 'publishing consistently across channels'], mistake: 'assembling a costly tool stack before proving a format, audience, and publishing cadence', beginner: 'Choose one creation tool and one distribution home, then publish enough to learn where quality or time actually breaks down.', professional: 'Established creators should prioritize brand control, collaboration, rights, archives, analytics, automation, and revenue integrations.', trend: 'Creator platforms are compressing scripting, recording, editing, translation, clipping, and distribution into connected production pipelines.', differentiator: 'whether the tool removes production friction without making the creator sound or look interchangeable', personas: ['New creator', 'Newsletter writer', 'Video creator', 'Creator team', 'Media business'] },
};

export function editorialFor(category: Category) { return EDITORIAL[category.slug] ?? EDITORIAL.assistant; }

export function categoryIntroduction(category: Category, products: Product[]) {
  const e = editorialFor(category);
  const top = [...products].sort((a, b) => b.rating - a.rating)[0]?.name ?? 'the leading options';
  const jobs = e.jobs.join(', ');
  return [
    `${category.name} tools are ${e.definition}. That broad label matters less than the job you are trying to complete: ${jobs}. The strongest product is not necessarily the one with the most AI features. It is the one that fits the inputs you already have, produces an output you can inspect, and removes a meaningful step without hiding important decisions. This guide compares ${products.length} reviewed option${products.length === 1 ? '' : 's'} using the same product taxonomy that powers AIToolBet reviews, so a newly categorized product can enter the shortlist without rebuilding this page by hand.`,
    `Who actually needs this software? ${e.audiences.join(', ')} are common buyers, but their requirements are not interchangeable. A solo user can often tolerate manual exports and a lightweight free plan. A team needs shared context, permissions, consistent processes, and an owner for rollout. Regulated or larger organizations must go further: security documentation, data-handling terms, identity controls, procurement, support, and a reliable exit path can matter more than an impressive demo. Write down the user, task, frequency, input, required output, and reviewer before comparing subscriptions.`,
    `The most common purchasing mistake is ${e.mistake}. Another is comparing plans by headline price while overlooking usage limits, paid add-ons, implementation time, and the human work required to check output. Ratings help establish a shortlist, but they compress very different experiences into one number. Read the limitations, inspect the supported platforms, and trial a real task with realistic source material. If a vendor cannot explain what happens to your data or how an output was produced, treat that uncertainty as a product limitation rather than an item to resolve after purchase.`,
    `For a first purchase, the sensible recommendation is straightforward. ${e.beginner} ${top} currently leads this category by our rating sort, but that is a starting point—not a universal verdict. Use a free plan or short trial to complete the same task two or three times. Note time to useful output, corrections needed, export friction, and whether you would willingly repeat the process next week. A simple tool used consistently usually creates more value than an advanced platform whose setup never reaches the team.`,
    `Professional buyers should use a higher bar. ${e.professional} Build a small evaluation set that represents easy, typical, and difficult work. Score results before discussing vendor preference, and include the people who must review or receive the output. Check integration depth rather than accepting an integration logo: ask what data moves, in which direction, how often, and with whose permissions. A product earns a premium when it reduces a durable bottleneck, not merely when it bundles more generation credits.`,
    `The current direction of the market is also relevant. ${e.trend} That can make workflows faster, but it also makes provenance, permissions, and failure recovery more important. Favor products that let a person see intermediate work, correct context, and approve consequential actions. Novel capabilities change quickly; dependable workflow design changes slowly. The practical trend to watch is not which vendor adds the newest button, but which one turns capability into a transparent routine your team can govern.`,
    `Make the final decision around ${e.differentiator}. Compare the free-plan boundary, platform support, setup time, collaboration, templates, automation, integrations, AI quality, and enterprise readiness in the matrix below. Then read the full reviews for the two closest candidates and keep an alternative in reserve. A good buying decision has a named use case, a budget that includes adoption, a measurable success condition, and a date to reassess. That discipline protects beginners from overbuying and gives professionals a defensible reason to standardize.`,
  ];
}
