export type ToolCapability = {
  strengths: string[];
  primaryJobs: string[];
  complements: string[];
  businesses: string[];
  contribution: string;
  starterAction: string;
  nextAction: string;
  primaryRole: string;
  responsibility: string;
  stackStage: 'plan' | 'build' | 'refine' | 'publish' | 'market' | 'automate' | 'operate';
};

const fallbackCapability: ToolCapability = {
  strengths: ['specialist software', 'focused execution'],
  primaryJobs: ['Complete the product-specific task named in its review facts'],
  complements: ['ChatGPT', 'Canva', 'MailerLite', 'Notion'],
  businesses: ['Specialized Service Business', 'Digital Product Business', 'Local Agency'],
  contribution: 'Perform the specific product role confirmed by the review facts; do not describe it with generic drafting, planning, or workflow language.',
  starterAction: 'Use the product for the narrow job its review facts explicitly support, then verify the output before selling or publishing it.',
  nextAction: 'Add only the next tool needed for the missing step, such as publishing, payment, email capture, visual polish, or client handoff.',
  primaryRole: 'Specialist software for the role described in its product facts.',
  responsibility: 'Complete one confirmed product-specific job.',
  stackStage: 'operate',
};

export const toolCapabilities: Record<string, ToolCapability> = {
  chatgpt: { strengths: ['requirements writing', 'analysis', 'brainstorming', 'documentation', 'file review'], primaryJobs: ['Write requirements', 'Draft documentation', 'Create user stories', 'Analyze source notes'], complements: ['Canva', 'MailerLite', 'Notion', 'Shopify'], businesses: ['AI Content Agency', 'Freelance Copywriting Business', 'Prompt Library Business'], contribution: 'Writes requirements, documentation, user stories, technical specifications, customer scripts, and source-grounded drafts for human review.', starterAction: 'Turn one messy customer problem into requirements, an outline, a checklist, a script, or a technical specification.', nextAction: 'Package the best prompts and editing checklist so every client project starts from the same intake process.', primaryRole: 'Planning and writing assistant for requirements, documentation, analysis, and structured drafts.', responsibility: 'Plan and document the work before another tool builds, publishes, or automates it.', stackStage: 'plan' },
  claude: { strengths: ['long documents', 'careful writing', 'research synthesis', 'policy drafts'], primaryJobs: ['Summarize long PDFs', 'Compare contracts', 'Draft executive memos', 'Synthesize interviews'], complements: ['Notion', 'ChatGPT', 'Grammarly', 'MailerLite'], businesses: ['Research Briefing Service', 'Executive Memo Studio', 'Policy Documentation Business'], contribution: 'Reads long source material and produces organized summaries, memos, risks, and next-step drafts for human review.', starterAction: 'Upload one source packet and create a decision-ready brief with assumptions and open questions.', nextAction: 'Create reusable briefing templates for each client type so research quality stays consistent.', primaryRole: 'Long-context research and document analysis assistant.', responsibility: 'Condense large source materials into decision-ready briefs.', stackStage: 'plan' },
  canva: { strengths: ['graphic design', 'templates', 'presentations', 'printables', 'brand kits'], primaryJobs: ['Design social posts', 'Create presentation decks', 'Build lead magnets', 'Make worksheets', 'Export print-ready PDFs'], complements: ['ChatGPT', 'Leonardo AI', 'MailerLite', 'Hostinger'], businesses: ['Pinterest Management Agency', 'Brand Design Studio', 'Teacher Resource Store', 'Digital Product Business'], contribution: 'Designs editable marketing graphics, template sets, slide decks, lead magnets, printables, and brand assets.', starterAction: 'Create one branded template set with examples, export previews, and editable customer instructions.', nextAction: 'Sell the template, publish a portfolio page, and collect emails from people who download free samples.', primaryRole: 'Visual design workspace for editable marketing and presentation assets.', responsibility: 'Design the customer-facing visual asset.', stackStage: 'refine' },
  'leonardo-ai': { strengths: ['AI image generation', 'product mockups', 'game assets', 'marketing visuals'], primaryJobs: ['Generate product mockups', 'Create Pinterest graphics', 'Design social media images', 'Produce marketing assets'], complements: ['Canva', 'ChatGPT', 'Shopify', 'MailerLite'], businesses: ['Print-on-Demand Store', 'Pinterest Management Agency', 'Product Mockup Studio'], contribution: 'Generates original product images, lifestyle mockups, backgrounds, and campaign visuals that designers can refine before publishing.', starterAction: 'Generate a small set of consistent product or lifestyle images for one niche offer.', nextAction: 'Build a reusable prompt and style guide so visual batches match across ads, pins, and storefronts.', primaryRole: 'AI image generator for product visuals and campaign imagery.', responsibility: 'Create original images and mockups.', stackStage: 'build' },
  elevenlabs: { strengths: ['voice generation', 'narration', 'audio localization', 'voiceovers'], primaryJobs: ['Generate voiceovers', 'Narrate tutorials', 'Produce audiobook audio', 'Create podcast intros'], complements: ['Canva', 'Descript', 'Pictory', 'ChatGPT'], businesses: ['YouTube Automation Agency', 'Audiobook Production Service', 'Course Creation Business'], contribution: 'Creates narration, explainer audio, podcast intros, localized voice tracks, and tutorial voiceovers from approved scripts.', starterAction: 'Record or generate one short narration from a script and match pacing to the target platform.', nextAction: 'Create voice, script, and editing standards so each new video or lesson sounds consistent.', primaryRole: 'AI voice platform for narration and voiceover production.', responsibility: 'Produce the spoken audio track.', stackStage: 'build' },
  hostinger: { strengths: ['website hosting', 'landing pages', 'business websites', 'WordPress'], primaryJobs: ['Host websites', 'Launch landing pages', 'Sell digital products', 'Create business websites'], complements: ['Canva', 'ChatGPT', 'MailerLite', 'Shopify'], businesses: ['Small Business Website Agency', 'Local Marketing Agency', 'Digital Product Business'], contribution: 'Hosts production websites, landing pages, WordPress sites, domains, portfolios, and download pages.', starterAction: 'Publish a simple one-page offer with proof, pricing, contact form, and one clear call to action.', nextAction: 'Add email capture, analytics, and a repeatable launch checklist for every new client or product.', primaryRole: 'Web hosting and site publishing platform.', responsibility: 'Publish the website or landing page.', stackStage: 'publish' },
  shopify: { strengths: ['ecommerce', 'payments', 'digital products', 'print on demand'], primaryJobs: ['Build online stores', 'Take payments', 'Sell digital downloads', 'Test print-on-demand products'], complements: ['ChatGPT', 'Canva', 'MailerLite', 'Leonardo AI'], businesses: ['Online Store', 'Print-on-Demand Store', 'Digital Product Business'], contribution: 'Runs the storefront, product pages, checkout, payments, discounts, and selling path for physical or digital products.', starterAction: 'Launch one focused product page with real photos or mockups, clear benefits, and a checkout test.', nextAction: 'Add abandoned-cart email, customer segmentation, and product bundles once the first sales prove demand.', primaryRole: 'Ecommerce platform for storefronts and checkout.', responsibility: 'Sell products and process orders.', stackStage: 'publish' },
  mailerlite: { strengths: ['email newsletters', 'lead magnets', 'automations', 'landing pages'], primaryJobs: ['Capture email leads', 'Send newsletters', 'Automate welcome sequences', 'Deliver lead magnets'], complements: ['Canva', 'ChatGPT', 'Hostinger', 'Shopify'], businesses: ['Email Marketing Agency', 'Creator Newsletter Business', 'Digital Product Business'], contribution: 'Captures leads, delivers downloads, sends newsletters, and runs simple welcome sequences after someone opts in.', starterAction: 'Create a lead magnet form and a three-email welcome sequence tied to one offer.', nextAction: 'Segment buyers, subscribers, and prospects so follow-up messages match what each person downloaded or purchased.', primaryRole: 'Email marketing platform for lead capture and newsletters.', responsibility: 'Capture leads and send email follow-up.', stackStage: 'market' },
  brevo: { strengths: ['CRM', 'email automation', 'transactional email', 'SMS campaigns'], primaryJobs: ['Manage contacts', 'Automate email sequences', 'Send transactional email', 'Run SMS campaigns'], complements: ['Hostinger', 'ChatGPT', 'Canva', 'Shopify'], businesses: ['CRM Setup Service', 'Email Automation Agency', 'Local Marketing Agency'], contribution: 'Stores contacts in a CRM, triggers email automation, sends transactional messages, and coordinates follow-up across email or SMS.', starterAction: 'Create contact lists, one intake form, and an onboarding automation that follows up after a lead submits interest.', nextAction: 'Add lifecycle segments, sales reminders, and transactional messages for customers who buy or book.', primaryRole: 'CRM and marketing automation platform.', responsibility: 'Automate customer follow-up from CRM data.', stackStage: 'automate' },
  notion: { strengths: ['docs', 'databases', 'project tracking', 'knowledge bases'], primaryJobs: ['Build client portals', 'Track content calendars', 'Create SOP libraries', 'Manage deliverables'], complements: ['ChatGPT', 'Canva', 'MailerLite', 'Slack'], businesses: ['Client Portal Setup Service', 'Operations Template Store', 'Content Agency'], contribution: 'Organizes briefs, SOPs, status, assets, approvals, and reusable client-delivery templates in one workspace.', starterAction: 'Build one delivery dashboard with intake, due dates, assets, feedback, and final links.', nextAction: 'Turn the dashboard into a template you can reuse for clients or sell as a digital product.', primaryRole: 'Workspace for documents, databases, project tracking, and SOPs.', responsibility: 'Organize the operating system for the work.', stackStage: 'operate' },
  cursor: { strengths: ['AI coding', 'codebase editing', 'debugging', 'refactoring'], primaryJobs: ['Build SaaS features', 'Refactor components', 'Debug application errors', 'Write tests'], complements: ['GitHub Copilot', 'ChatGPT', 'Replit AI', 'Vercel'], businesses: ['Micro-SaaS Studio', 'Internal Dashboard Agency', 'Client Portal Business'], contribution: 'Edits existing codebases, implements feature changes, explains files, refactors components, and debugs app behavior.', starterAction: 'Build one narrow feature in an existing app and test it before adding scope.', nextAction: 'Add auth, payments, analytics, and maintainable handoff docs after users validate the feature.', primaryRole: 'AI code editor for modifying an existing codebase.', responsibility: 'Implement and refactor application code.', stackStage: 'build' },
  'github-copilot': { strengths: ['code completion', 'test generation', 'refactoring', 'IDE assistance'], primaryJobs: ['Refactor code', 'Explain logic', 'Generate tests', 'Complete functions'], complements: ['Bolt.new', 'Lovable', 'Replit AI', 'Cursor'], businesses: ['Micro-SaaS Studio', 'Developer Tooling Agency', 'Internal App Consultancy'], contribution: 'Reviews generated code, refactors complex functions, explains implementation logic, and writes missing tests inside the developer workflow.', starterAction: 'Open the codebase in your IDE, refactor the riskiest file, and add tests around the behavior before deployment.', nextAction: 'Use pull-request review, test generation, and code explanations to make the app maintainable for future developers.', primaryRole: 'IDE coding assistant for code completion, refactoring, and tests.', responsibility: 'Improve code quality inside the IDE.', stackStage: 'refine' },
  'replit-ai': { strengths: ['browser IDE', 'debugging', 'deployment', 'collaboration'], primaryJobs: ['Run apps in the browser', 'Debug runtime errors', 'Deploy prototypes', 'Collaborate on code'], complements: ['Bolt.new', 'GitHub Copilot', 'ChatGPT', 'Hostinger'], businesses: ['Prototype Studio', 'Student App Builds', 'Client Demo Agency'], contribution: 'Runs, debugs, deploys, and shares applications from a browser-based development environment.', starterAction: 'Import or create the app, run it in the browser, fix runtime errors, and deploy a shareable demo.', nextAction: 'Invite collaborators, verify environment variables, and keep deployment notes for handoff.', primaryRole: 'Browser IDE for running, debugging, deploying, and collaborating on apps.', responsibility: 'Run and deploy the application.', stackStage: 'publish' },
  'bolt-new': { strengths: ['prompt-to-app generation', 'full-stack prototypes', 'rapid MVPs'], primaryJobs: ['Generate full-stack apps', 'Create prototypes from prompts', 'Scaffold web app features'], complements: ['GitHub Copilot', 'Replit AI', 'Lovable', 'ChatGPT'], businesses: ['Micro-SaaS Studio', 'MVP Prototyping Agency', 'Client Portal Business'], contribution: 'Generates the first working full-stack application from prompts so a builder can test the core product idea quickly.', starterAction: 'Prompt one narrow full-stack app with data, pages, and basic interactions, then verify the generated project actually runs.', nextAction: 'Move the prototype into code review, UX refinement, and deployment once the main path works.', primaryRole: 'Prompt-to-full-stack app generator.', responsibility: 'Generate the first working application.', stackStage: 'build' },
  lovable: { strengths: ['visual app building', 'UI iteration', 'frontend refinement', 'feature edits'], primaryJobs: ['Refine app UI', 'Iterate features visually', 'Adjust frontend flows'], complements: ['Bolt.new', 'GitHub Copilot', 'Replit AI', 'Hostinger'], businesses: ['MVP Design Studio', 'SaaS Landing App Agency', 'Client Portal Business'], contribution: 'Refines UI visually, adjusts app flows, and iterates features without forcing every frontend change through manual coding.', starterAction: 'Take one working app screen and improve layout, copy, states, and user flow until a buyer can understand it.', nextAction: 'Hand the refined app to code review, testing, and deployment tools before calling it production-ready.', primaryRole: 'Visual app builder for frontend and UX iteration.', responsibility: 'Refine the user experience.', stackStage: 'refine' },
  pictory: { strengths: ['video editing', 'text-to-video', 'social clips'], primaryJobs: ['Edit marketing videos', 'Turn scripts into videos', 'Create short clips'], complements: ['ElevenLabs', 'ChatGPT', 'Canva', 'Descript'], businesses: ['YouTube Automation Agency', 'Short-Form Video Service', 'Course Promo Studio'], contribution: 'Turns scripts, articles, or recorded material into edited marketing videos and social clips.', starterAction: 'Convert one approved script into a short video with captions, visuals, and a platform-specific export.', nextAction: 'Batch variations for YouTube, Shorts, and ads once the winning structure is clear.', primaryRole: 'Video creation and editing tool for script-based marketing videos.', responsibility: 'Edit and assemble videos.', stackStage: 'refine' },
};

export function capabilityFor(slug: string): ToolCapability {
  return toolCapabilities[slug] ?? fallbackCapability;
}

export function uniqueResponsibilities(tools: { name: string; slug?: string }[]) {
  const used = new Set<string>();
  return tools.filter((tool) => {
    const responsibility = capabilityFor(tool.slug ?? '').responsibility;
    if (used.has(responsibility)) return false;
    used.add(responsibility);
    return true;
  });
}
