export type ToolCapability = {
  strengths: string[];
  primaryJobs: string[];
  complements: string[];
  businesses: string[];
  contribution: string;
  starterAction: string;
  nextAction: string;
};

const fallbackCapability: ToolCapability = {
  strengths: ['client deliverables', 'repeatable workflows', 'drafting', 'quality review'],
  primaryJobs: ['Create client-ready drafts', 'Build reusable templates', 'Prepare deliverables', 'Document repeatable processes'],
  complements: ['ChatGPT', 'Canva', 'MailerLite', 'Notion'],
  businesses: ['Freelance Service Business', 'Digital Product Business', 'Local Marketing Agency'],
  contribution: 'Own the main deliverable while the rest of the stack handles research, presentation, sales, and follow-up.',
  starterAction: 'Create one polished sample deliverable for a narrow audience.',
  nextAction: 'Turn the sample into a fixed-scope offer with a checklist, price, and revision limit.',
};

export const toolCapabilities: Record<string, ToolCapability> = {
  chatgpt: { strengths: ['writing', 'analysis', 'brainstorming', 'coding help', 'file review'], primaryJobs: ['Draft blog posts and emails', 'Turn notes into outlines', 'Create customer scripts', 'Analyze documents', 'Generate code examples'], complements: ['Canva', 'MailerLite', 'Notion', 'Shopify'], businesses: ['AI Content Agency', 'Freelance Copywriting Business', 'Prompt Library Business'], contribution: 'Turns raw notes, interviews, research, or customer FAQs into structured drafts that a human can fact-check and polish.', starterAction: 'Start by turning one messy customer problem into a useful outline, checklist, script, or article draft.', nextAction: 'Package your best prompts and editing checklist so every client project starts from the same intake process.' },
  claude: { strengths: ['long documents', 'careful writing', 'research synthesis', 'policy drafts'], primaryJobs: ['Summarize long PDFs', 'Compare contracts', 'Draft executive memos', 'Synthesize interviews'], complements: ['Notion', 'ChatGPT', 'Grammarly', 'MailerLite'], businesses: ['Research Briefing Service', 'Executive Memo Studio', 'Policy Documentation Business'], contribution: 'Reads long source material and produces organized summaries, memos, risks, and next-step drafts for human review.', starterAction: 'Upload one source packet and create a decision-ready brief with assumptions and open questions.', nextAction: 'Create reusable briefing templates for each client type so research quality stays consistent.' },
  canva: { strengths: ['graphic design', 'templates', 'presentations', 'printables', 'brand kits'], primaryJobs: ['Design social posts', 'Create presentation decks', 'Build lead magnets', 'Make worksheets', 'Export print-ready PDFs'], complements: ['ChatGPT', 'Leonardo AI', 'MailerLite', 'Hostinger'], businesses: ['Pinterest Management Agency', 'Brand Design Studio', 'Teacher Resource Store', 'Digital Product Business'], contribution: 'Turns ideas into editable designs, templates, slide decks, lead magnets, printables, and social assets clients can reuse.', starterAction: 'Create one branded template set with examples, export previews, and editable customer instructions.', nextAction: 'Sell the template, publish a portfolio page, and collect emails from people who download free samples.' },
  'leonardo-ai': { strengths: ['AI image generation', 'product mockups', 'game assets', 'marketing visuals'], primaryJobs: ['Generate product mockups', 'Create Pinterest graphics', 'Design social media images', 'Produce marketing assets'], complements: ['Canva', 'ChatGPT', 'Shopify', 'MailerLite'], businesses: ['Print-on-Demand Store', 'Pinterest Management Agency', 'Product Mockup Studio'], contribution: 'Generates original visual concepts, lifestyle mockups, backgrounds, and campaign imagery that designers can refine in Canva or product pages.', starterAction: 'Generate a small set of consistent product or lifestyle images for one niche offer.', nextAction: 'Build a reusable prompt and style guide so visual batches match across ads, pins, and storefronts.' },
  elevenlabs: { strengths: ['voice generation', 'narration', 'audio localization', 'voiceovers'], primaryJobs: ['Generate voiceovers', 'Narrate tutorials', 'Produce audiobook audio', 'Create podcast intros'], complements: ['Canva', 'Descript', 'Pictory', 'ChatGPT'], businesses: ['YouTube Automation Agency', 'Audiobook Production Service', 'Course Creation Business'], contribution: 'Creates polished narration, explainer audio, podcast intros, and tutorial voiceovers from approved scripts.', starterAction: 'Record or generate one short narration from a script and match pacing to the target platform.', nextAction: 'Create voice, script, and editing standards so each new video or lesson sounds consistent.' },
  hostinger: { strengths: ['website hosting', 'landing pages', 'business websites', 'WordPress'], primaryJobs: ['Host websites', 'Launch landing pages', 'Sell digital products', 'Create business websites'], complements: ['Canva', 'ChatGPT', 'MailerLite', 'Shopify'], businesses: ['Small Business Website Agency', 'Local Marketing Agency', 'Digital Product Business'], contribution: 'Provides the website, domain, landing page, or WordPress home for offers, portfolios, client sites, and download pages.', starterAction: 'Publish a simple one-page offer with proof, pricing, contact form, and one clear call to action.', nextAction: 'Add email capture, analytics, and a repeatable launch checklist for every new client or product.' },
  shopify: { strengths: ['ecommerce', 'payments', 'digital products', 'print on demand'], primaryJobs: ['Build online stores', 'Take payments', 'Sell digital downloads', 'Test print-on-demand products'], complements: ['ChatGPT', 'Canva', 'MailerLite', 'Leonardo AI'], businesses: ['Online Store', 'Print-on-Demand Store', 'Digital Product Business'], contribution: 'Handles product pages, checkout, discounts, basic storefront operations, and the selling path for physical or digital products.', starterAction: 'Launch one focused product page with real photos or mockups, clear benefits, and a checkout test.', nextAction: 'Add abandoned-cart email, customer segmentation, and product bundles once the first sales prove demand.' },
  mailerlite: { strengths: ['email newsletters', 'lead magnets', 'automations', 'landing pages'], primaryJobs: ['Capture email leads', 'Send newsletters', 'Automate welcome sequences', 'Deliver lead magnets'], complements: ['Canva', 'ChatGPT', 'Hostinger', 'Shopify'], businesses: ['Email Marketing Agency', 'Creator Newsletter Business', 'Digital Product Business'], contribution: 'Captures leads, delivers downloads, sends welcome sequences, and nurtures subscribers after they interact with content or products.', starterAction: 'Create a lead magnet form and a three-email welcome sequence tied to one offer.', nextAction: 'Segment buyers, subscribers, and prospects so follow-up messages match what each person downloaded or purchased.' },
  notion: { strengths: ['docs', 'databases', 'project tracking', 'knowledge bases'], primaryJobs: ['Build client portals', 'Track content calendars', 'Create SOP libraries', 'Manage deliverables'], complements: ['ChatGPT', 'Canva', 'MailerLite', 'Slack'], businesses: ['Client Portal Setup Service', 'Operations Template Store', 'Content Agency'], contribution: 'Keeps briefs, SOPs, status, assets, approvals, and reusable templates in one workspace.', starterAction: 'Build one delivery dashboard with intake, due dates, assets, feedback, and final links.', nextAction: 'Turn the dashboard into a template you can reuse for clients or sell as a digital product.' },
  cursor: { strengths: ['AI coding', 'codebase editing', 'debugging', 'refactoring'], primaryJobs: ['Build SaaS features', 'Refactor components', 'Debug application errors', 'Write tests'], complements: ['GitHub Copilot', 'ChatGPT', 'Replit AI', 'Vercel'], businesses: ['Micro-SaaS Studio', 'Internal Dashboard Agency', 'Client Portal Business'], contribution: 'Edits real codebases, explains existing files, generates implementation drafts, and helps debug specific app behavior.', starterAction: 'Build one narrow feature in an existing app and test it before adding scope.', nextAction: 'Add auth, payments, analytics, and maintainable handoff docs after users validate the feature.' },
};

export function capabilityFor(slug: string): ToolCapability {
  return toolCapabilities[slug] ?? fallbackCapability;
}
