import Link from 'next/link';
import { notFound } from 'next/navigation';
import { readReviewDraft } from '@/lib/content/storage';
import { saveDraft, publishDraft } from '../../actions';

export const dynamic = 'force-dynamic';
const order = ['overview','pros','cons','pricingSummary','whoShouldBuy','whoShouldAvoid','useCases','faq','verdict'] as const;
export default async function DraftReview({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const draft = await readReviewDraft(slug); if (!draft) notFound();
  return <main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100"><form action={saveDraft} className="mx-auto max-w-5xl space-y-8"><input type="hidden" name="slug" value={slug} /><div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin/content" className="text-blue-200">← Dashboard</Link><h1 className="mt-3 text-4xl font-bold">Review draft: {draft.productSnapshot.name}</h1><p className="mt-2 text-slate-300">Edit each generated section independently before publishing.</p>{draft.metadata ? <p className="mt-2 text-xs text-slate-400">Prompt {draft.metadata.promptVersion} · {draft.metadata.provider} · cache {draft.metadata.cacheHash.slice(0, 10)}</p> : null}</div><div className="flex gap-3"><Link href={`/admin/content/reviews/${slug}/preview`} className="rounded-full border border-white/15 px-5 py-3 font-semibold">Preview</Link><button className="rounded-full bg-blue-500 px-5 py-3 font-semibold text-white">Save Draft</button><button formAction={publishDraft} className="rounded-full bg-emerald-500 px-5 py-3 font-semibold text-slate-950">Publish</button></div></div><section className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/5 p-6"><p className="text-sm text-slate-400">Quality Score</p><p className="mt-2 text-4xl font-bold">{draft.quality?.overall ?? '—'}{draft.quality ? '/100' : ''}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm text-slate-300">{draft.quality ? Object.entries(draft.quality).filter(([key])=>key !== 'overall' && key !== 'recommendations').map(([key,value])=><p key={key}>{key}: {value as number}</p>) : null}</div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-6"><p className="text-sm text-slate-400">Missing Content</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-300">{(draft.missingContent?.missing.length ? draft.missingContent.missing : ['No critical gaps detected']).map((item)=><li key={item}>{item}</li>)}</ul></div></section>{order.map((key)=>{ const section = draft.sections[key]; if (!section) return null; const value = typeof section.content === 'string' ? section.content : key === 'faq' ? JSON.stringify(section.content, null, 2) : section.content.join('\n'); return <section key={key} className="rounded-3xl border border-white/10 bg-white/5 p-6"><div className="mb-4 flex items-center justify-between gap-4"><div><h2 className="text-2xl font-semibold">{section.title}</h2><p className="text-xs text-slate-400">Generated {new Date(section.generatedAt).toLocaleString()} with {section.model}</p></div><code className="rounded-full bg-slate-900 px-3 py-1 text-xs">npm run generate:review {slug} -- --section={key} --force</code></div><textarea name={key} rows={key === 'overview' || key === 'faq' ? 12 : 6} className="w-full rounded-2xl border border-white/10 bg-slate-900 p-4 font-mono text-sm text-slate-100" defaultValue={value} /></section>})}</form></main>;
}
