#!/usr/bin/env node
const fs = require('fs/promises');
const path = require('path');
const crypto = require('crypto');
const [command, slugArg, ...flags] = process.argv.slice(2);
const force = flags.includes('--force') || slugArg === '--force';
const onlySection = flags.find((flag) => flag.startsWith('--section='))?.split('=')[1];
const model = process.env.OPENAI_MODEL || 'gpt-4.1-mini';
const root = process.cwd();
const promptVersion = 'publishing-engine-v1';
const providerVersion = 'openai-responses-json-v1';
const sections = [['overview','Overview'],['pros','Pros'],['cons','Cons'],['pricingSummary','Pricing Summary'],['whoShouldBuy','Who Should Buy'],['whoShouldAvoid','Who Should Avoid'],['useCases','Use Cases'],['faq','FAQ'],['verdict','Final Verdict']];
async function readJson(file){ return JSON.parse(await fs.readFile(file,'utf8')); }
async function exists(file){ try{ await fs.access(file); return true;}catch{return false;} }
function stable(v){ if(Array.isArray(v)) return `[${v.map(stable).join(',')}]`; if(v && typeof v === 'object') return `{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${stable(x)}`).join(',')}}`; return JSON.stringify(v); }
function hash(v){ return crypto.createHash('sha256').update(stable(v)).digest('hex'); }
async function products(){ return (await fs.readdir(path.join(root,'products'))).filter(f=>f.endsWith('.json')).map(f=>f.replace(/\.json$/,'')); }
async function factPack(product){ const all = await Promise.all((await products()).map(slug=>readJson(path.join(root,'products',`${slug}.json`)))); const related = all.filter(p=>p.slug!==product.slug && ((p.primaryCategory && p.primaryCategory===product.primaryCategory) || (p.categories||[]).some(c=>(product.categories||[]).includes(c)))).slice(0,5); return { product: { slug:product.slug,name:product.name,tagline:product.tagline,description:product.description,rating:product.rating,reviewCount:product.reviewCount,categories:product.categories,primaryCategory:product.primaryCategory,secondaryCategories:product.secondaryCategories,tags:product.tags,pricing:product.pricing,pricingPlans:product.pricingPlans,platforms:product.platforms,setupTime:product.setupTime,bestFor:product.bestFor,users:product.users,features:product.features,pros:product.pros,cons:product.cons,audiences:product.audiences,notFor:product.notFor,useCases:product.useCases,faq:product.faq,screenshots:product.screenshots,heroImage:product.heroImage,seoTitle:product.seoTitle,metaDescription:product.metaDescription,seoKeywords:product.seoKeywords||product.keywords }, alternatives: product.alternatives || related.map(p=>({slug:p.slug,name:p.name,description:p.description})), comparisons: related.map(p=>({slug:`${product.slug}-vs-${p.slug}`,competitorSlug:p.slug,competitorName:p.name,competitorPricing:p.pricing,competitorRating:p.rating,competitorBestFor:p.bestFor,competitorFeatures:(p.features||[]).map(f=>f.title)})), existingComparisonRows: product.comparison }; }
function prompt(pack){ return { instructions:'Generate every content asset in one strict JSON response. Use only supplied facts. Do not invent prices, integrations, screenshots, awards, or benchmarks. FAQ questions must be product-specific. Buying guide, alternatives, comparison, and tutorial fields are reusable snippets, not full pages.', expectedJson:{review:{overview:['string'],pros:['string'],cons:['string'],whoShouldBuy:['string'],whoShouldAvoid:['string'],pricingSummary:'string',featureHighlights:['string'],verdict:'string',faq:[{question:'string',answer:'string'}]},buyingGuide:[{category:'string',whyMadeTheList:'string',bestUseCase:'string',whoShouldSkip:'string',topCompetitor:'string',quickSummary:'string'}],alternatives:[{slug:'string',name:'string',bestFor:'string',biggestStrength:'string',biggestWeakness:'string',whySomeoneWouldSwitch:'string'}],comparison:[{competitorSlug:'string',competitorName:'string',mainDifference:'string',whenProductWins:'string',whenCompetitorWins:'string',recommendation:'string'}],tutorial:{title:'string',steps:['string'],summary:'string'},seo:{title:'string',metaDescription:'string',openGraphDescription:'string',twitterDescription:'string',searchSnippet:'string',shortSummary:'string',longSummary:'string',scores:{uniqueness:0,keywordCoverage:0,contentCompleteness:0}},quality:{specificity:0,readability:0,productRelevance:0,seoCoverage:0,contentDepth:0,internalLinking:0,overall:0,recommendations:['string']},missingContent:{missing:['string'],recommendations:['string']}}, factPack:pack, promptVersion}; }
async function openaiJson(body){ if(!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY is required.'); const res = await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:[{role:'system',content:'You are an experienced software review editor. Write polished, factual, product-specific copy. Never invent facts. Return strict JSON.'},{role:'user',content:JSON.stringify(body)}],text:{format:{type:'json_object'}}})}); if(!res.ok) throw new Error(`OpenAI Responses API failed: ${res.status} ${await res.text()}`); const data=await res.json(); const text=data.output_text || (data.output||[]).flatMap(o=>o.content||[]).map(c=>c.text).filter(Boolean).join('\n'); return JSON.parse(text); }
function baseDraft(product, slug){ return { type:'review', slug, productSlug:slug, status:'draft', generatedAt:new Date().toISOString(), updatedAt:new Date().toISOString(), model, seo:{title:product.seoTitle||`${product.name} Review: ${product.tagline}`,metaDescription:product.metaDescription||product.description,canonical:product.canonicalUrl||`/${slug}`}, sections:{}, productSnapshot:{slug:product.slug,name:product.name,rating:product.rating,pricing:product.pricing,categories:product.categories,platforms:product.platforms,affiliateLink:product.affiliateLink,logo:product.logo,features:product.features}}; }
function put(draft,key,title,content){ draft.sections[key]={key,title,content,generatedAt:new Date().toISOString(),model,sourceFields:['one-response-fact-pack']}; }
async function generateReview(slug){ const product = await readJson(path.join(root,'products',`${slug}.json`)); const file = path.join(root,'content','drafts','reviews',`${slug}.json`); const pack = await factPack(product); const cacheHash = hash({pack,promptVersion,providerVersion,model}); if(await exists(file) && !force && !onlySection){ const existing=await readJson(file); if(existing.metadata?.cacheHash===cacheHash){ console.log(`Draft cache hit for ${slug}`); return; } }
 let draft = await exists(file) ? await readJson(file) : baseDraft(product, slug); if(onlySection) throw new Error('--section regeneration is available in the Next.js generator; CLI generation now uses the one-response engine.'); const result=await openaiJson(prompt(pack)); put(draft,'overview','Overview',result.review.overview); put(draft,'pros','Pros',result.review.pros); put(draft,'cons','Cons',result.review.cons); put(draft,'pricingSummary','Pricing Summary',result.review.pricingSummary); put(draft,'whoShouldBuy','Who Should Buy',result.review.whoShouldBuy); put(draft,'whoShouldAvoid','Who Should Avoid',result.review.whoShouldAvoid); put(draft,'useCases','Use Cases',result.review.featureHighlights); put(draft,'faq','FAQ',result.review.faq); put(draft,'verdict','Final Verdict',result.review.verdict); draft.seo={...draft.seo,...result.seo,canonical:product.canonicalUrl||`/${slug}`}; draft.assets={buyingGuide:result.buyingGuide,alternatives:result.alternatives,comparison:result.comparison,tutorial:result.tutorial}; draft.quality=result.quality; draft.missingContent=result.missingContent; draft.metadata={promptVersion,generatedDate:new Date().toISOString(),model,provider:'openai-responses',providerVersion,cacheHash,sourceHash:hash(pack),cached:false}; draft.status='needs_review'; draft.updatedAt=new Date().toISOString(); await fs.mkdir(path.dirname(file),{recursive:true}); await fs.writeFile(file,JSON.stringify(draft,null,2)+'\n'); console.log(`Generated one-response review assets for ${slug}`); }
async function all(){ for(const slug of await products()) await generateReview(slug); }
(async()=>{ if(command==='generate:review') return generateReview(slugArg); if(command==='generate:all-reviews'||command==='generate:all') return all(); if(['generate:buying-guides','generate:tutorials','generate:alternatives'].includes(command)) return console.log(`${command} now uses reusable assets generated by generate:review.`); throw new Error(`Unknown command ${command}`); })().catch((e)=>{ console.error(e); process.exit(1); });
