#!/usr/bin/env node
const fs = require('fs/promises');
const path = require('path');
const sections = [
  ['overview','Overview',['name','tagline','description','features','categories','platforms']], ['pros','Pros',['pros','features','rating']], ['cons','Cons',['cons','notFor']], ['pricingSummary','Pricing Summary',['pricing','pricingPlans']], ['whoShouldBuy','Who Should Buy',['audiences','bestFor','useCases']], ['whoShouldAvoid','Who Should Avoid',['notFor','cons']], ['useCases','Use Cases',['useCases','features']], ['faq','FAQ',['faq','pricing','features']], ['verdict','Final Verdict',['rating','review','pros','cons','bestFor']]
];
const [command, slugArg, ...flags] = process.argv.slice(2);
const force = flags.includes('--force') || slugArg === '--force';
const onlySection = flags.find((flag) => flag.startsWith('--section='))?.split('=')[1];
const model = process.env.OPENAI_MODEL || 'gpt-4.1-mini';
const root = process.cwd();
async function readJson(file){ return JSON.parse(await fs.readFile(file,'utf8')); }
async function exists(file){ try{ await fs.access(file); return true;}catch{return false;} }
function pick(product, fields){ return Object.fromEntries(fields.map((field)=>[field, product[field]])); }
function expectedShape(section){ if(section==='faq') return '{ "content": [{ "question": "...", "answer": "..." }] }'; if(['overview','pros','cons','whoShouldBuy','whoShouldAvoid','useCases'].includes(section)) return '{ "content": ["..."] }'; return '{ "content": "..." }'; }
async function openaiJson(prompt){ if(!process.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY is required.'); const res = await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:[{role:'system',content:['You are an experienced software review editor.','Write polished, factual, SEO-friendly review copy.','Never mention AI assistance, content generation, prompts, or internal workflow.','Do not invent facts. Use only the provided product JSON.','Return strict JSON matching the requested shape.'].join('\n')},{role:'user',content:JSON.stringify(prompt)}],text:{format:{type:'json_object'}}})}); if(!res.ok) throw new Error(`OpenAI Responses API failed: ${res.status} ${await res.text()}`); const data=await res.json(); const text=data.output_text || (data.output||[]).flatMap((o)=>o.content||[]).map((c)=>c.text).filter(Boolean).join('\n'); return JSON.parse(text); }
async function generateReview(slug){ const product = await readJson(path.join(root,'products',`${slug}.json`)); const file = path.join(root,'content','drafts','reviews',`${slug}.json`); if(await exists(file) && !force && !onlySection){ console.log(`Draft exists for ${slug}; use --force to regenerate.`); return; } let draft = await exists(file) ? await readJson(file) : { type:'review', slug, productSlug:slug, status:'draft', generatedAt:new Date().toISOString(), updatedAt:new Date().toISOString(), model, seo:{title:product.seoTitle||`${product.name} Review: ${product.tagline}`, metaDescription:product.metaDescription||product.description, canonical:product.canonicalUrl||`/${slug}`}, sections:{}, productSnapshot:{slug:product.slug,name:product.name,rating:product.rating,pricing:product.pricing,categories:product.categories,platforms:product.platforms,affiliateLink:product.affiliateLink,logo:product.logo,features:product.features}};
 for(const [key,title,sourceFields] of sections){ if(onlySection && key !== onlySection) continue; if(draft.sections[key] && !force && !onlySection) continue; const result = await openaiJson({ instructions:`Generate only the ${title} section. Keep it publication-ready and fact-bound.`, expectedJson: expectedShape(key), productJson: JSON.stringify(pick(product, sourceFields), null, 2)}); draft.sections[key] = {key,title,content:result.content,generatedAt:new Date().toISOString(),model,sourceFields}; }
 draft.status='needs_review'; draft.updatedAt=new Date().toISOString(); await fs.mkdir(path.dirname(file),{recursive:true}); await fs.writeFile(file,JSON.stringify(draft,null,2)+'\n'); console.log(`Generated review draft for ${slug}`); }
async function all(){ const files=(await fs.readdir(path.join(root,'products'))).filter(f=>f.endsWith('.json')); for(const f of files) await generateReview(f.replace(/\.json$/,'')); }
(async()=>{ if(command==='generate:review') return generateReview(slugArg); if(command==='generate:all-reviews'||command==='generate:all') return all(); if(['generate:buying-guides','generate:tutorials','generate:alternatives'].includes(command)) return console.log(`${command} scaffold is ready; use product metadata and prompts in lib/content/prompts.ts to enable this content type.`); throw new Error(`Unknown command ${command}`); })().catch((e)=>{ console.error(e); process.exit(1); });
