import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check } from 'lucide-react';
import { ProductLogo } from '@/components/ProductLogo';
import { AffiliateButton } from '@/components/affiliate-button';
import { getProducts, type Product } from '@/lib/products';
import { findComparisonPair, getComparisonPairs, getFeatureRows, getPrimaryCategoryHref, getProductSummary, getRecommendationButtons, getRelatedComparisonProducts, getScoreRows, getWinner, getWinnerCards, listBestFor } from '@/lib/comparisons';

type Props = { params: Promise<{ comparison: string }> };

export async function generateStaticParams() { const products = await getProducts(); return getComparisonPairs(products).map((pair) => ({ comparison: pair.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { comparison } = await params; const products = await getProducts(); const pair = findComparisonPair(products, comparison); if (!pair) return {}; const title = `${pair.toolA.name} vs ${pair.toolB.name} (2026): Which Tool Is Better?`; const description = `${pair.toolA.name} vs ${pair.toolB.name}: compare best-fit use cases, real feature differences, ratings, pricing, pros, cons, and recommendations.`; return { title, description, alternates: { canonical: `/compare/${pair.slug}` }, openGraph: { title, description, url: `/compare/${pair.slug}`, type: 'article' }, twitter: { card: 'summary_large_image', title, description } }; }

export default async function ComparisonPage({ params }: Props) {
  const { comparison } = await params; const products = await getProducts(); const pair = findComparisonPair(products, comparison); if (!pair) notFound();
  const { toolA, toolB } = pair; const winner = getWinner(toolA, toolB); const related = getRelatedComparisonProducts(toolA, products, 6).filter((product) => product.slug !== toolB.slug).slice(0, 4); const recommendations = getRecommendationButtons(toolA, toolB);
  const verdict = `${toolA.name} is the stronger choice when your priority is ${listBestFor(toolA).slice(0, 2).join(' or ').toLowerCase()}. ${toolB.name} is better when you need ${listBestFor(toolB).slice(0, 2).join(' or ').toLowerCase()}. If you want the safest overall pick for this matchup, ${winner.name} has the edge, but the right decision depends on which workflow matters most.`;
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', headline: `${toolA.name} vs ${toolB.name} (2026)`, description: verdict, mainEntityOfPage: `/compare/${pair.slug}`, about: [toolA.name, toolB.name] };
  return <main className="min-h-screen bg-radial-blue pb-20 text-white">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="mx-auto max-w-7xl px-6 pb-16 pt-24 lg:px-8 lg:pt-32"><div className="grid gap-8 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><HeroTool product={toolA} /><div className="text-center text-4xl font-black text-blue-200">VS</div><HeroTool product={toolB} /></div><div className="glass mt-10 rounded-[2rem] p-8 text-center"><p className="text-sm font-semibold uppercase tracking-[.3em] text-blue-300">Expert recommendation</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">{toolA.name} vs {toolB.name} (2026)</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-300">{verdict}</p><div className="mt-8 grid gap-4 md:grid-cols-3"><Mini title="Quick winner" value={winner.name} /><MiniList title={`${toolA.name} best for`} items={listBestFor(toolA)} /><MiniList title={`${toolB.name} best for`} items={listBestFor(toolB)} /></div></div></section>
    <Section eyebrow="Winner cards" title="Category winners based on product ratings"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{getWinnerCards(toolA, toolB).map((card) => <Mini key={card.title} title={card.title} value={`${card.product.name} — ${card.reason}`} />)}</div></Section>
    <Section eyebrow="Score breakdown" title="Category scores"><ScoreBreakdown toolA={toolA} toolB={toolB} /></Section>
    <Section eyebrow="Feature comparison" title="Real side-by-side differences"><FeatureTable toolA={toolA} toolB={toolB} /></Section>
    <Section eyebrow="Pros and cons" title="What each product actually does well"><div className="grid gap-6 lg:grid-cols-2"><ProsCons product={toolA} /><ProsCons product={toolB} /></div></Section>
    <Section eyebrow="Who should choose this?" title="Best-fit recommendations"><div className="grid gap-6 lg:grid-cols-2"><Choose product={toolA} /><Choose product={toolB} /></div></Section>
    <Section eyebrow="Not sure which tool fits you?" title="Pick your workflow"><div className="grid gap-4 md:grid-cols-3">{recommendations.map((item) => <LinkCard key={item.intent} href={`/${item.product.slug}`} title={`${item.intent}: ${item.product.name}`} />)}</div></Section>
    <Section eyebrow="Pricing" title="Pricing plans side by side"><div className="grid gap-6 lg:grid-cols-2"><Pricing product={toolA} /><Pricing product={toolB} /></div></Section>
    <Section eyebrow="Final verdict" title={`${toolA.name} vs ${toolB.name}: the bottom line`}><div className="glass rounded-3xl p-8 text-lg leading-8 text-slate-300">{verdict}</div></Section>
    <Section eyebrow="Related content" title="Keep comparing"><div className="grid gap-4 md:grid-cols-3"><LinkCard href={`/${toolA.slug}`} title={`${toolA.name} review`} /><LinkCard href={`/${toolB.slug}`} title={`${toolB.name} review`} /><LinkCard href={getPrimaryCategoryHref(toolA)} title={`${toolA.category ?? toolA.categoryBadge ?? 'Category'} tools`} />{(toolA.alternatives ?? []).slice(0, 1).map((alt) => <LinkCard key={alt.slug} href={`/${alt.slug}`} title={`${toolA.name} alternative: ${alt.name}`} />)}<LinkCard href={getPrimaryCategoryHref(toolA)} title={`Best ${toolA.category ?? 'tools'}`} />{related.map((product) => <LinkCard key={product.slug} href={`/compare/${toolA.slug}-vs-${product.slug}`} title={`${toolA.name} vs ${product.name}`} />)}</div></Section>
  </main>;
}
function HeroTool({ product }: { product: Product }) { return <div className="glass rounded-[2rem] p-8 text-center"><ProductLogo logo={product.logo} name={product.name} size={80} className="mx-auto rounded-2xl" /><h2 className="mt-5 text-3xl font-bold">{product.name}</h2><p className="mt-3 text-slate-300">{getProductSummary(product)}</p><AffiliateButton href={product.affiliateLink}>Try {product.name}</AffiliateButton></div>; }
function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-7xl px-6 py-14 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[.3em] text-blue-300">{eyebrow}</p><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">{title}</h2><div className="mt-10">{children}</div></section>; }
function Mini({ title, value }: { title: string; value: string }) { return <div className="glass rounded-3xl p-6"><p className="text-sm font-semibold uppercase tracking-[.2em] text-blue-300">{title}</p><p className="mt-3 text-xl font-bold text-white">{value}</p></div>; }
function MiniList({ title, items }: { title: string; items: string[] }) { return <div className="glass rounded-3xl p-6 text-left"><p className="text-sm font-semibold uppercase tracking-[.2em] text-blue-300">{title}</p><ul className="mt-3 space-y-2 text-white">{items.map((item) => <li key={item}>• {item}</li>)}</ul></div>; }
function ScoreBreakdown({ toolA, toolB }: { toolA: Product; toolB: Product }) { return <div className="grid gap-5">{getScoreRows(toolA, toolB).map((row) => <div key={row.key} className="glass rounded-3xl p-5"><div className="mb-3 flex items-center justify-between"><strong>{row.label}</strong><span className="text-slate-300">{toolA.name}: {row.a.toFixed(1)} · {toolB.name}: {row.b.toFixed(1)}</span></div><div className="grid gap-3 md:grid-cols-2"><Bar name={toolA.name} value={row.a} /><Bar name={toolB.name} value={row.b} /></div></div>)}</div>; }
function Bar({ name, value }: { name: string; value: number }) { return <div><div className="mb-1 flex justify-between text-sm text-slate-300"><span>{name}</span><span>{value.toFixed(1)}/5</span></div><div className="h-3 rounded-full bg-white/10"><div className="h-3 rounded-full bg-blue-300" style={{ width: `${Math.min(value * 20, 100)}%` }} /></div></div>; }
function FeatureTable({ toolA, toolB }: { toolA: Product; toolB: Product }) { return <Table headers={[toolA.name, toolB.name]} rows={getFeatureRows(toolA, toolB).map((row) => [row.feature, row.a, row.b])} />; }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[780px] text-left"><thead className="bg-white/10"><tr><th className="p-5">Feature</th>{headers.map((header) => <th className="p-5" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-t border-white/10"><th className="p-5 align-top text-white">{row[0]}</th>{row.slice(1).map((value, index) => <td key={`${row[0]}-${index}`} className="bg-blue-400/5 p-5 align-top text-slate-300">{value}</td>)}</tr>)}</tbody></table></div>; }
function ProsCons({ product }: { product: Product }) { const pros = product.strengths ?? product.pros; const cons = product.weaknesses ?? product.cons; return <div className="glass rounded-3xl p-6"><h3 className="text-2xl font-bold">{product.name}</h3><h4 className="mt-6 font-semibold text-emerald-300">Pros</h4><ul className="mt-3 space-y-3">{pros.map((item) => <li key={item} className="flex gap-2 text-slate-200"><Check className="h-5 w-5 shrink-0" />{item}</li>)}</ul><h4 className="mt-6 font-semibold text-amber-300">Cons</h4><ul className="mt-3 space-y-3">{cons.map((item) => <li key={item} className="text-slate-300">• {item}</li>)}</ul></div>; }
function Choose({ product }: { product: Product }) { return <div className="glass rounded-3xl p-6"><h3 className="text-2xl font-bold">Choose {product.name} if...</h3><ul className="mt-5 space-y-4 text-slate-300">{(product.idealUsers ?? listBestFor(product)).map((item) => <li key={item} className="flex gap-2"><Check className="h-5 w-5 shrink-0 text-emerald-300" />{item}</li>)}</ul></div>; }
function Pricing({ product }: { product: Product }) { return <div className="space-y-4"><h3 className="text-2xl font-bold">{product.name}</h3>{product.pricingPlans.map((plan) => <div key={plan.name} className="glass rounded-3xl p-6"><p className="text-xl font-bold">{plan.name} <span className="text-blue-200">{plan.price}</span></p><p className="mt-2 text-slate-300">{plan.description}</p></div>)}</div>; }
function LinkCard({ href, title }: { href: string; title: string }) { return <Link href={href} className="glass rounded-3xl p-6 font-semibold transition hover:border-blue-300/40">{title} →</Link>; }
